
// Generated by Cadence Genus(TM) Synthesis Solution 22.16-s078_1
// Generated on: Mar  5 2026 19:00:16 -03 (Mar  5 2026 22:00:16 UTC)

// Verification Directory fv/i2c_master_controller 

module i2c_master_controller(clk, rst, address, data_in, enable, rw,
     data_out, ready, i2c_sda, i2c_scl);
  input clk, rst, enable, rw;
  input [6:0] address;
  input [7:0] data_in;
  output [7:0] data_out;
  output ready;
  inout i2c_sda, i2c_scl;
  wire clk, rst, enable, rw;
  wire [6:0] address;
  wire [7:0] data_in;
  wire [7:0] data_out;
  wire ready;
  wire i2c_sda, i2c_scl;
  wire [3:0] counter;
  wire [3:0] state;
  wire [7:0] address_reg;
  wire [7:0] write_data_reg;
  wire [2:0] clk_counter;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, i2c_clk, n_0, n_1, n_3,
       n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_25, n_27, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97, n_98, n_99, n_100, n_102, n_103, n_104, n_105;
  wire n_106, n_108, n_109, n_134, n_137, n_138, scl_enable,
       sda_drive_en;
  wire sda_out;
  DFFHQX1 \counter_reg[1] (.CK (i2c_clk), .D (n_109), .Q (counter[1]));
  DFFNSRX1 sda_out_reg(.RN (1'b1), .SN (n_106), .CKN (i2c_clk), .D
       (n_108), .Q (sda_out), .QN (UNCONNECTED));
  SDFFQX1 \counter_reg[0] (.CK (i2c_clk), .D (counter[0]), .SI (n_86),
       .SE (n_134), .Q (counter[0]));
  SDFFQX1 \counter_reg[2] (.CK (i2c_clk), .D (counter[2]), .SI (n_95),
       .SE (n_134), .Q (counter[2]));
  MXI2XL g1770__2398(.A (n_10), .B (n_90), .S0 (n_134), .Y (n_109));
  MX2X1 g1768__5107(.A (sda_out), .B (n_105), .S0 (n_97), .Y (n_108));
  DFFNSRX1 sda_drive_en_reg(.RN (1'b1), .SN (n_106), .CKN (i2c_clk), .D
       (n_104), .Q (sda_drive_en), .QN (UNCONNECTED0));
  NAND2BXL g1771__4319(.AN (n_73), .B (n_103), .Y (n_105));
  MX3XL g1769__8428(.A (state[1]), .B (n_23), .C (sda_drive_en), .S0
       (n_1), .S1 (n_94), .Y (n_104));
  SDFFRHQX1 \state_reg[0] (.RN (n_106), .CK (i2c_clk), .D (state[0]),
       .SI (n_22), .SE (n_84), .Q (state[0]));
  OAI222XL g1794__5526(.A0 (n_137), .A1 (n_87), .B0 (n_102), .B1
       (n_83), .C0 (n_102), .C1 (n_137), .Y (n_103));
  AOI221X1 g1811__6783(.A0 (n_99), .A1 (n_57), .B0 (n_99), .B1 (n_102),
       .C0 (n_88), .Y (n_100));
  SDFFQX1 \data_out_reg[3] (.CK (i2c_clk), .D (data_out[3]), .SI
       (n_68), .SE (n_98), .Q (data_out[3]));
  SDFFQX1 \data_out_reg[2] (.CK (i2c_clk), .D (data_out[2]), .SI
       (n_71), .SE (n_98), .Q (data_out[2]));
  SDFFQX1 \data_out_reg[1] (.CK (i2c_clk), .D (data_out[1]), .SI
       (n_82), .SE (n_98), .Q (data_out[1]));
  SDFFQX1 \data_out_reg[4] (.CK (i2c_clk), .D (data_out[4]), .SI
       (n_69), .SE (n_98), .Q (data_out[4]));
  SDFFQX1 \data_out_reg[7] (.CK (i2c_clk), .D (data_out[7]), .SI
       (n_66), .SE (n_98), .Q (data_out[7]));
  SDFFQX1 \data_out_reg[6] (.CK (i2c_clk), .D (data_out[6]), .SI
       (n_65), .SE (n_98), .Q (data_out[6]));
  SDFFQX1 \data_out_reg[5] (.CK (i2c_clk), .D (data_out[5]), .SI
       (n_80), .SE (n_98), .Q (data_out[5]));
  SDFFQX1 \data_out_reg[0] (.CK (i2c_clk), .D (data_out[0]), .SI
       (n_78), .SE (n_98), .Q (data_out[0]));
  NAND3XL g1785__3680(.A (n_93), .B (n_75), .C (n_96), .Y (n_97));
  OAI211X1 g1784__1617(.A0 (n_40), .A1 (n_89), .B0 (n_59), .C0 (n_92),
       .Y (n_95));
  AND4XL g1789__2802(.A (n_27), .B (n_81), .C (n_93), .D (n_92), .Y
       (n_94));
  OAI22XL g1766__1705(.A0 (n_67), .A1 (n_79), .B0 (n_16), .B1 (n_62),
       .Y (n_91));
  AOI211XL g1783__5122(.A0 (counter[1]), .A1 (counter[0]), .B0 (n_89),
       .C0 (n_85), .Y (n_90));
  DFFNSRX1 scl_enable_reg(.RN (n_106), .SN (1'b1), .CKN (i2c_clk), .D
       (n_74), .Q (scl_enable), .QN (UNCONNECTED1));
  OAI22XL g1817__8246(.A0 (n_63), .A1 (n_70), .B0 (i2c_sda), .B1
       (n_61), .Y (n_88));
  NAND4XL g1821__7098(.A (n_55), .B (n_45), .C (n_41), .D (n_47), .Y
       (n_87));
  NAND2BXL g1772__6131(.AN (n_85), .B (counter[0]), .Y (n_86));
  NAND2BXL g1786__1881(.AN (n_76), .B (n_64), .Y (n_84));
  NAND4XL g1816__5115(.A (n_58), .B (n_44), .C (n_60), .D (n_48), .Y
       (n_83));
  NOR2XL g1780__7482(.A (n_81), .B (n_52), .Y (n_82));
  NOR2XL g1778__4733(.A (n_81), .B (n_50), .Y (n_80));
  NOR4X1 g1773__6161(.A (state[3]), .B (n_3), .C (n_15), .D (n_31), .Y
       (n_79));
  NOR2XL g1782__9315(.A (n_81), .B (n_56), .Y (n_78));
  SDFFQX1 \address_reg_reg[0] (.CK (i2c_clk), .D (address_reg[0]), .SI
       (rw), .SE (n_77), .Q (address_reg[0]));
  SDFFQX1 \address_reg_reg[5] (.CK (i2c_clk), .D (address_reg[5]), .SI
       (address[4]), .SE (n_77), .Q (address_reg[5]));
  SDFFQX1 \write_data_reg_reg[1] (.CK (i2c_clk), .D
       (write_data_reg[1]), .SI (data_in[1]), .SE (n_77), .Q
       (write_data_reg[1]));
  SDFFQX1 \write_data_reg_reg[2] (.CK (i2c_clk), .D
       (write_data_reg[2]), .SI (data_in[2]), .SE (n_77), .Q
       (write_data_reg[2]));
  SDFFQX1 \write_data_reg_reg[0] (.CK (i2c_clk), .D
       (write_data_reg[0]), .SI (data_in[0]), .SE (n_77), .Q
       (write_data_reg[0]));
  SDFFQX1 \address_reg_reg[7] (.CK (i2c_clk), .D (address_reg[7]), .SI
       (address[6]), .SE (n_77), .Q (address_reg[7]));
  SDFFQX1 \write_data_reg_reg[4] (.CK (i2c_clk), .D
       (write_data_reg[4]), .SI (data_in[4]), .SE (n_77), .Q
       (write_data_reg[4]));
  SDFFRHQX1 \state_reg[2] (.RN (n_106), .CK (i2c_clk), .D (state[2]),
       .SI (n_24), .SE (n_76), .Q (state[2]));
  OAI21X1 g1787__9945(.A0 (n_81), .A1 (rst), .B0 (n_30), .Y (n_98));
  NOR2XL g1814__2883(.A (n_102), .B (n_137), .Y (n_75));
  NOR2XL g1765__2346(.A (n_29), .B (n_73), .Y (n_74));
  MX2X1 g1764__1666(.A (state[1]), .B (n_34), .S0 (n_76), .Y (n_72));
  SDFFQX1 \write_data_reg_reg[6] (.CK (i2c_clk), .D
       (write_data_reg[6]), .SI (data_in[6]), .SE (n_77), .Q
       (write_data_reg[6]));
  SDFFQX1 \write_data_reg_reg[7] (.CK (i2c_clk), .D
       (write_data_reg[7]), .SI (data_in[7]), .SE (n_77), .Q
       (write_data_reg[7]));
  SDFFQX1 \address_reg_reg[1] (.CK (i2c_clk), .D (address_reg[1]), .SI
       (address[0]), .SE (n_77), .Q (address_reg[1]));
  SDFFQX1 \address_reg_reg[2] (.CK (i2c_clk), .D (address_reg[2]), .SI
       (address[1]), .SE (n_77), .Q (address_reg[2]));
  SDFFQX1 \write_data_reg_reg[5] (.CK (i2c_clk), .D
       (write_data_reg[5]), .SI (data_in[5]), .SE (n_77), .Q
       (write_data_reg[5]));
  SDFFQX1 \address_reg_reg[3] (.CK (i2c_clk), .D (address_reg[3]), .SI
       (address[2]), .SE (n_77), .Q (address_reg[3]));
  INVXL g1807(.A (n_85), .Y (n_92));
  SDFFQX1 \address_reg_reg[4] (.CK (i2c_clk), .D (address_reg[4]), .SI
       (address[3]), .SE (n_77), .Q (address_reg[4]));
  SDFFQX1 \write_data_reg_reg[3] (.CK (i2c_clk), .D
       (write_data_reg[3]), .SI (data_in[3]), .SE (n_77), .Q
       (write_data_reg[3]));
  SDFFQX1 \address_reg_reg[6] (.CK (i2c_clk), .D (address_reg[6]), .SI
       (address[5]), .SE (n_77), .Q (address_reg[6]));
  NOR2XL g1775__7410(.A (n_81), .B (n_32), .Y (n_71));
  INVXL g1823(.A (n_137), .Y (n_70));
  NOR2XL g1777__6417(.A (n_81), .B (n_38), .Y (n_69));
  NOR2XL g1776__5477(.A (n_81), .B (n_35), .Y (n_68));
  MX2X1 g1818__2398(.A (n_39), .B (n_49), .S0 (n_67), .Y (n_93));
  NOR2XL g1781__6260(.A (n_81), .B (n_36), .Y (n_66));
  NOR2XL g1779__4319(.A (n_81), .B (n_37), .Y (n_65));
  OAI221X1 g1795__8428(.A0 (n_63), .A1 (n_62), .B0 (enable), .B1
       (n_19), .C0 (n_67), .Y (n_64));
  NAND2XL g1809__5526(.A (n_61), .B (n_96), .Y (n_85));
  OA22X1 g1832__6783(.A0 (n_33), .A1 (n_59), .B0 (n_0), .B1 (n_51), .Y
       (n_60));
  AOI22XL g1834__3680(.A0 (address_reg[2]), .A1 (n_54), .B0
       (address_reg[3]), .B1 (n_53), .Y (n_58));
  INVXL g1824(.A (n_81), .Y (n_57));
  MXI2XL g1800__2802(.A (data_out[0]), .B (i2c_sda), .S0 (n_63), .Y
       (n_56));
  AOI22XL g1845__1705(.A0 (write_data_reg[2]), .A1 (n_54), .B0
       (write_data_reg[3]), .B1 (n_53), .Y (n_55));
  MXI2XL g1792__5122(.A (i2c_sda), .B (data_out[1]), .S0 (n_51), .Y
       (n_52));
  MXI2XL g1804__8246(.A (i2c_sda), .B (data_out[5]), .S0 (n_18), .Y
       (n_50));
  NOR2XL g1796__7098(.A (state[0]), .B (n_49), .Y (n_73));
  AOI33XL g1835__6131(.A0 (address_reg[4]), .A1 (counter[2]), .A2
       (n_89), .B0 (counter[2]), .B1 (address_reg[5]), .B2 (n_138), .Y
       (n_48));
  AOI33XL g1846__1881(.A0 (write_data_reg[4]), .A1 (counter[2]), .A2
       (n_89), .B0 (counter[2]), .B1 (write_data_reg[5]), .B2 (n_138),
       .Y (n_47));
  AOI22XL g1844__5115(.A0 (write_data_reg[6]), .A1 (n_43), .B0
       (write_data_reg[7]), .B1 (n_42), .Y (n_45));
  AOI22XL g1833__7482(.A0 (address_reg[6]), .A1 (n_43), .B0
       (address_reg[7]), .B1 (n_42), .Y (n_44));
  AOI33XL g1843__4733(.A0 (write_data_reg[0]), .A1 (n_40), .A2 (n_89),
       .B0 (n_40), .B1 (write_data_reg[1]), .B2 (n_138), .Y (n_41));
  NAND2XL g1826__6161(.A (state[0]), .B (n_25), .Y (n_61));
  OR2X1 g1829__9315(.A (state[0]), .B (n_39), .Y (n_81));
  MXI2XL g1803__9945(.A (i2c_sda), .B (data_out[4]), .S0 (n_12), .Y
       (n_38));
  MXI2XL g1799__2883(.A (i2c_sda), .B (data_out[6]), .S0 (n_7), .Y
       (n_37));
  MXI2XL g1801__2346(.A (i2c_sda), .B (data_out[7]), .S0 (n_11), .Y
       (n_36));
  MXI2XL g1802__1666(.A (i2c_sda), .B (data_out[3]), .S0 (n_17), .Y
       (n_35));
  AOI221X1 g1788__7410(.A0 (n_33), .A1 (state[1]), .B0 (state[1]), .B1
       (i2c_sda), .C0 (state[2]), .Y (n_34));
  MXI2XL g1805__6417(.A (i2c_sda), .B (data_out[2]), .S0 (n_14), .Y
       (n_32));
  NOR2XL g1810__5477(.A (n_62), .B (n_21), .Y (n_31));
  INVXL g1791(.A (n_77), .Y (n_30));
  NAND2XL g1815__2398(.A (state[0]), .B (n_29), .Y (n_96));
  NAND2XL g1825__5107(.A (state[3]), .B (n_62), .Y (n_49));
  NOR2XL g1828__6260(.A (state[0]), .B (n_27), .Y (n_102));
  NOR2XL g1774__4319(.A (n_20), .B (i2c_sda), .Y (n_24));
  AND4X1 g1798__8428(.A (n_23), .B (n_6), .C (n_22), .D (n_106), .Y
       (n_77));
  DFFSHQX1 i2c_clk_reg(.SN (n_106), .CK (clk), .D (n_9), .Q (i2c_clk));
  INVXL g1831(.A (i2c_sda), .Y (n_21));
  NOR2XL g1839__5526(.A (state[3]), .B (n_20), .Y (n_25));
  NOR2XL g1822__6783(.A (state[3]), .B (n_19), .Y (n_29));
  INVXL g1830(.A (n_99), .Y (n_63));
  NAND2XL g1857__3680(.A (counter[2]), .B (n_138), .Y (n_18));
  INVXL g1849(.A (n_17), .Y (n_53));
  NAND2XL g1841__1617(.A (n_16), .B (n_15), .Y (n_39));
  INVXL g1854(.A (n_14), .Y (n_54));
  NAND2XL g1859__2802(.A (n_40), .B (n_138), .Y (n_51));
  NAND2XL g1851__1705(.A (counter[2]), .B (n_89), .Y (n_12));
  INVXL g1850(.A (n_11), .Y (n_42));
  NAND3BXL g1836__5122(.AN (counter[0]), .B (n_40), .C (n_10), .Y
       (n_99));
  INVXL g1838(.A (n_19), .Y (n_62));
  OAI22X1 g1767__8246(.A0 (i2c_clk), .A1 (n_8), .B0 (clk_counter[0]),
       .B1 (n_5), .Y (n_9));
  NAND3BXL g1856__7098(.AN (counter[0]), .B (counter[1]), .C (n_40), .Y
       (n_14));
  NAND2XL g1862__6131(.A (n_40), .B (n_89), .Y (n_59));
  NAND3XL g1840__1881(.A (state[2]), .B (n_23), .C (n_16), .Y (n_27));
  NAND3XL g1852__5115(.A (counter[1]), .B (counter[0]), .C (n_40), .Y
       (n_17));
  INVXL g1855(.A (n_7), .Y (n_43));
  AND2X1 g1819__7482(.A (n_4), .B (enable), .Y (n_6));
  NAND2XL g1793__4733(.A (scl_enable), .B (n_5), .Y (i2c_scl));
  NOR2XL g1847__6161(.A (n_23), .B (n_4), .Y (n_15));
  NAND2XL g1848__9315(.A (state[1]), .B (n_4), .Y (n_20));
  NAND2XL g1842__9945(.A (n_4), .B (n_23), .Y (n_19));
  NOR2XL g1808__2883(.A (enable), .B (n_4), .Y (n_3));
  NAND3BXL g1858__2346(.AN (counter[0]), .B (counter[1]), .C
       (counter[2]), .Y (n_7));
  NAND3XL g1853__7410(.A (counter[1]), .B (counter[2]), .C
       (counter[0]), .Y (n_11));
  NOR2XL g1797__6417(.A (state[3]), .B (n_67), .Y (n_76));
  TBUFX1 g3__2398(.A (sda_out), .OE (sda_drive_en), .Y (i2c_sda));
  NOR2XL g1863__5107(.A (counter[0]), .B (counter[1]), .Y (n_89));
  INVXL g1806(.A (rst), .Y (n_106));
  NAND2XL g1812__6260(.A (state[2]), .B (state[0]), .Y (n_1));
  NOR2XL g1813__4319(.A (state[0]), .B (state[3]), .Y (n_22));
  INVX1 g1874(.A (i2c_clk), .Y (n_5));
  INVXL g1869(.A (state[0]), .Y (n_67));
  INVXL g1868(.A (counter[2]), .Y (n_40));
  INVXL g1870(.A (address_reg[1]), .Y (n_0));
  INVXL g1864(.A (address_reg[0]), .Y (n_33));
  INVXL g1873(.A (counter[1]), .Y (n_10));
  INVXL g1865(.A (state[2]), .Y (n_4));
  AOI21X1 g2(.A0 (n_96), .A1 (n_100), .B0 (rst), .Y (n_134));
  DFFRX1 \clk_counter_reg[0] (.RN (n_106), .CK (clk), .D (n_8), .Q
       (clk_counter[0]), .QN (n_8));
  DFFRX1 \state_reg[3] (.RN (n_106), .CK (i2c_clk), .D (n_91), .Q
       (state[3]), .QN (n_16));
  DFFRX1 \state_reg[1] (.RN (n_106), .CK (i2c_clk), .D (n_72), .Q
       (state[1]), .QN (n_23));
  NOR3BXL g1918(.AN (n_29), .B (state[0]), .C (rst), .Y (ready));
  NOR2BX1 g1919(.AN (n_25), .B (state[0]), .Y (n_137));
  NOR2BX1 g1920(.AN (counter[0]), .B (counter[1]), .Y (n_138));
endmodule

