
// Generated by Cadence Genus(TM) Synthesis Solution 22.16-s078_1
// Generated on: Mar 18 2026 18:16:42 -03 (Mar 18 2026 21:16:42 UTC)

// Verification Directory fv/i2c_master_controller 

module i2c_master_controller(clk, rst, address, data_in, enable, rw,
     data_out, ready, i2c_sda, i2c_scl);
  input clk, rst, enable, rw;
  input [6:0] address;
  input [7:0] data_in;
  output [7:0] data_out;
  output ready;
  inout i2c_sda, i2c_scl;
  wire clk, rst, enable, rw;
  wire [6:0] address;
  wire [7:0] data_in;
  wire [7:0] data_out;
  wire ready;
  wire i2c_sda, i2c_scl;
  wire [3:0] counter;
  wire [3:0] state;
  wire [7:0] address_reg;
  wire [7:0] write_data_reg;
  wire [2:0] clk_counter;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, i2c_clk, n_0, n_1, n_2,
       n_3;
  wire n_4, n_5, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_33, n_34, n_35, n_36, n_37;
  wire n_38, n_39, n_40, n_41, n_42, n_43, n_44, n_45;
  wire n_46, n_47, n_48, n_49, n_50, n_51, n_52, n_53;
  wire n_54, n_55, n_56, n_57, n_58, n_59, n_60, n_61;
  wire n_62, n_63, n_64, n_65, n_66, n_67, n_68, n_69;
  wire n_70, n_71, n_72, n_73, n_74, n_75, n_76, n_77;
  wire n_78, n_79, n_80, n_81, n_82, n_83, n_84, n_85;
  wire n_86, n_87, n_88, n_89, n_90, n_91, n_92, n_93;
  wire n_94, n_95, n_96, n_97, n_98, n_99, n_100, n_101;
  wire n_102, n_103, n_104, n_105, n_106, n_107, n_108, n_109;
  wire n_110, n_111, n_112, n_113, n_114, n_115, n_116, n_118;
  wire n_119, n_120, n_121, n_122, n_123, n_124, n_125, n_126;
  wire n_127, n_128, n_152, scl_enable, sda_drive_en, sda_out;
  DFFNSRX1 sda_out_reg(.RN (1'b1), .SN (n_125), .CKN (i2c_clk), .D
       (n_128), .Q (sda_out), .QN (UNCONNECTED));
  MX2X1 g2320__2398(.A (sda_out), .B (n_126), .S0 (n_55), .Y (n_128));
  DFFHQX1 \counter_reg[0] (.CK (i2c_clk), .D (n_127), .Q (counter[0]));
  OAI211X1 g2321__5107(.A0 (n_101), .A1 (n_122), .B0 (n_1), .C0
       (n_124), .Y (n_127));
  NAND4BXL g2345__6260(.AN (n_118), .B (n_58), .C (n_103), .D (n_94),
       .Y (n_126));
  DFFHQX1 \counter_reg[1] (.CK (i2c_clk), .D (n_123), .Q (counter[1]));
  DFFHQX1 \counter_reg[2] (.CK (i2c_clk), .D (n_121), .Q (counter[2]));
  DFFHQX1 \data_out_reg[0] (.CK (i2c_clk), .D (n_115), .Q
       (data_out[0]));
  AOI21XL g2337__4319(.A0 (counter[0]), .A1 (n_28), .B0 (n_108), .Y
       (n_124));
  OAI211X1 g2325__8428(.A0 (n_33), .A1 (n_122), .B0 (n_59), .C0
       (n_120), .Y (n_123));
  OAI211X1 g2324__5526(.A0 (n_0), .A1 (n_36), .B0 (n_29), .C0 (n_120),
       .Y (n_121));
  DFFHQX1 \data_out_reg[6] (.CK (i2c_clk), .D (n_114), .Q
       (data_out[6]));
  OAI2BB1X1 g2310__6783(.A0N (state[3]), .A1N (n_50), .B0 (n_111), .Y
       (n_119));
  NAND4XL g2367__3680(.A (n_98), .B (n_104), .C (n_89), .D (n_97), .Y
       (n_118));
  DFFHQX1 \data_out_reg[2] (.CK (i2c_clk), .D (n_109), .Q
       (data_out[2]));
  DFFHQX1 \data_out_reg[4] (.CK (i2c_clk), .D (n_112), .Q
       (data_out[4]));
  DFFNSRX1 sda_drive_en_reg(.RN (1'b1), .SN (n_125), .CKN (i2c_clk), .D
       (n_107), .Q (sda_drive_en), .QN (UNCONNECTED0));
  DFFHQX1 \data_out_reg[3] (.CK (i2c_clk), .D (n_95), .Q (data_out[3]));
  DFFHQX1 \data_out_reg[7] (.CK (i2c_clk), .D (n_106), .Q
       (data_out[7]));
  NAND4XL g2307__1617(.A (n_22), .B (n_49), .C (n_38), .D (n_90), .Y
       (n_116));
  OAI21XL g2311__2802(.A0 (n_113), .A1 (n_83), .B0 (n_75), .Y (n_115));
  DFFHQX1 \data_out_reg[1] (.CK (i2c_clk), .D (n_99), .Q (data_out[1]));
  DFFHQX1 \data_out_reg[5] (.CK (i2c_clk), .D (n_105), .Q
       (data_out[5]));
  OAI21XL g2318__1705(.A0 (n_113), .A1 (n_65), .B0 (n_71), .Y (n_114));
  OAI21XL g2316__5122(.A0 (n_113), .A1 (n_69), .B0 (n_77), .Y (n_112));
  OAI211X1 g2338__8246(.A0 (state[1]), .A1 (n_85), .B0 (state[2]), .C0
       (n_64), .Y (n_111));
  OAI211X1 g2308__7098(.A0 (n_67), .A1 (n_86), .B0 (n_68), .C0 (n_74),
       .Y (n_110));
  OAI21XL g2314__6131(.A0 (n_113), .A1 (n_70), .B0 (n_79), .Y (n_109));
  INVXL g2340(.A (n_120), .Y (n_108));
  MX2X1 g2322__1881(.A (sda_drive_en), .B (n_13), .S0 (n_52), .Y
       (n_107));
  OAI21XL g2319__5115(.A0 (n_113), .A1 (n_56), .B0 (n_82), .Y (n_106));
  OAI21XL g2317__7482(.A0 (n_113), .A1 (n_54), .B0 (n_78), .Y (n_105));
  AOI33XL g2397__4733(.A0 (n_57), .A1 (n_102), .A2 (n_41), .B0 (n_96),
       .B1 (address_reg[7]), .B2 (n_100), .Y (n_104));
  AOI33XL g2398__6161(.A0 (address_reg[0]), .A1 (n_102), .A2 (n_88),
       .B0 (n_101), .B1 (address_reg[1]), .B2 (n_100), .Y (n_103));
  OAI21XL g2312__9315(.A0 (n_113), .A1 (n_60), .B0 (n_81), .Y (n_99));
  AOI32X1 g2399__9945(.A0 (address_reg[5]), .A1 (n_91), .A2 (n_100),
       .B0 (state[3]), .B1 (n_72), .Y (n_98));
  AOI33XL g2400__2883(.A0 (address_reg[3]), .A1 (n_93), .A2 (n_100),
       .B0 (n_96), .B1 (write_data_reg[7]), .B2 (n_92), .Y (n_97));
  OAI21XL g2315__2346(.A0 (n_113), .A1 (n_53), .B0 (n_76), .Y (n_95));
  NAND2XL g2354__1666(.A (n_35), .B (n_62), .Y (n_120));
  AOI33XL g2380__7410(.A0 (write_data_reg[3]), .A1 (n_93), .A2 (n_92),
       .B0 (n_91), .B1 (write_data_reg[5]), .B2 (n_92), .Y (n_94));
  AOI32X1 g2334__6417(.A0 (state[0]), .A1 (state[3]), .A2 (n_37), .B0
       (n_63), .B1 (n_39), .Y (n_90));
  AOI33XL g2401__5477(.A0 (write_data_reg[0]), .A1 (n_73), .A2 (n_88),
       .B0 (n_101), .B1 (write_data_reg[1]), .B2 (n_92), .Y (n_89));
  OAI221X1 g2326__2398(.A0 (n_2), .A1 (n_86), .B0 (n_44), .B1 (n_85),
       .C0 (n_46), .Y (n_87));
  SDFFQX1 \address_reg_reg[4] (.CK (i2c_clk), .D (address[3]), .SI
       (address_reg[4]), .SE (n_84), .Q (address_reg[4]));
  SDFFQX1 \address_reg_reg[1] (.CK (i2c_clk), .D (address[0]), .SI
       (address_reg[1]), .SE (n_84), .Q (address_reg[1]));
  SDFFQX1 \write_data_reg_reg[0] (.CK (i2c_clk), .D (data_in[0]), .SI
       (write_data_reg[0]), .SE (n_84), .Q (write_data_reg[0]));
  SDFFQX1 \address_reg_reg[6] (.CK (i2c_clk), .D (address[5]), .SI
       (address_reg[6]), .SE (n_84), .Q (address_reg[6]));
  SDFFQX1 \write_data_reg_reg[2] (.CK (i2c_clk), .D (data_in[2]), .SI
       (write_data_reg[2]), .SE (n_84), .Q (write_data_reg[2]));
  SDFFQX1 \write_data_reg_reg[1] (.CK (i2c_clk), .D (data_in[1]), .SI
       (write_data_reg[1]), .SE (n_84), .Q (write_data_reg[1]));
  MXI2XL g2349__5107(.A (i2c_sda), .B (data_out[0]), .S0 (n_42), .Y
       (n_83));
  SDFFQX1 \address_reg_reg[5] (.CK (i2c_clk), .D (address[4]), .SI
       (address_reg[5]), .SE (n_84), .Q (address_reg[5]));
  SDFFQX1 \address_reg_reg[7] (.CK (i2c_clk), .D (address[6]), .SI
       (address_reg[7]), .SE (n_84), .Q (address_reg[7]));
  SDFFQX1 \address_reg_reg[3] (.CK (i2c_clk), .D (address[2]), .SI
       (address_reg[3]), .SE (n_84), .Q (address_reg[3]));
  SDFFQX1 \write_data_reg_reg[7] (.CK (i2c_clk), .D (data_in[7]), .SI
       (write_data_reg[7]), .SE (n_84), .Q (write_data_reg[7]));
  SDFFQX1 \address_reg_reg[2] (.CK (i2c_clk), .D (address[1]), .SI
       (address_reg[2]), .SE (n_84), .Q (address_reg[2]));
  SDFFQX1 \write_data_reg_reg[5] (.CK (i2c_clk), .D (data_in[5]), .SI
       (write_data_reg[5]), .SE (n_84), .Q (write_data_reg[5]));
  SDFFQX1 \write_data_reg_reg[4] (.CK (i2c_clk), .D (data_in[4]), .SI
       (write_data_reg[4]), .SE (n_84), .Q (write_data_reg[4]));
  SDFFQX1 \write_data_reg_reg[3] (.CK (i2c_clk), .D (data_in[3]), .SI
       (write_data_reg[3]), .SE (n_84), .Q (write_data_reg[3]));
  SDFFQX1 \write_data_reg_reg[6] (.CK (i2c_clk), .D (data_in[6]), .SI
       (write_data_reg[6]), .SE (n_84), .Q (write_data_reg[6]));
  SDFFQX1 \address_reg_reg[0] (.CK (i2c_clk), .D (rw), .SI
       (address_reg[0]), .SE (n_84), .Q (address_reg[0]));
  NAND2XL g2335__6260(.A (data_out[7]), .B (n_80), .Y (n_82));
  NAND2XL g2329__4319(.A (data_out[1]), .B (n_80), .Y (n_81));
  NAND2XL g2330__8428(.A (data_out[2]), .B (n_80), .Y (n_79));
  NAND2XL g2327__5526(.A (data_out[5]), .B (n_80), .Y (n_78));
  NAND2XL g2332__6783(.A (data_out[4]), .B (n_80), .Y (n_77));
  NAND2XL g2331__3680(.A (data_out[3]), .B (n_80), .Y (n_76));
  NAND2XL g2328__1617(.A (data_out[0]), .B (n_80), .Y (n_75));
  AOI32X1 g2347__2802(.A0 (address_reg[0]), .A1 (n_73), .A2 (n_43), .B0
       (n_66), .B1 (n_72), .Y (n_74));
  NAND2XL g2339__1705(.A (data_out[6]), .B (n_80), .Y (n_71));
  MXI2XL g2341__5122(.A (data_out[2]), .B (i2c_sda), .S0 (n_152), .Y
       (n_70));
  MXI2XL g2342__8246(.A (data_out[4]), .B (i2c_sda), .S0 (n_34), .Y
       (n_69));
  AOI31X1 g2336__7098(.A0 (n_67), .A1 (n_66), .A2 (n_88), .B0 (n_61),
       .Y (n_68));
  MXI2XL g2358__6131(.A (data_out[6]), .B (i2c_sda), .S0 (n_30), .Y
       (n_65));
  OAI2BB1X1 g2366__1881(.A0N (n_63), .A1N (n_47), .B0 (n_15), .Y
       (n_64));
  NAND2BXL g2369__5115(.AN (n_61), .B (n_45), .Y (n_62));
  MXI2XL g2346__7482(.A (i2c_sda), .B (data_out[1]), .S0 (n_18), .Y
       (n_60));
  NAND2XL g2333__4733(.A (counter[1]), .B (n_122), .Y (n_59));
  NAND3BXL g2396__6161(.AN (n_27), .B (n_57), .C (n_73), .Y (n_58));
  MXI2XL g2348__9315(.A (i2c_sda), .B (data_out[7]), .S0 (n_20), .Y
       (n_56));
  OAI211X1 g2353__9945(.A0 (state[3]), .A1 (n_12), .B0 (n_40), .C0
       (n_51), .Y (n_55));
  MXI2XL g2352__2883(.A (i2c_sda), .B (data_out[5]), .S0 (n_17), .Y
       (n_54));
  MXI2XL g2351__2346(.A (i2c_sda), .B (data_out[3]), .S0 (n_21), .Y
       (n_53));
  NAND4XL g2359__1666(.A (n_4), .B (n_48), .C (n_51), .D (n_50), .Y
       (n_52));
  NAND2BXL g2368__7410(.AN (n_48), .B (n_47), .Y (n_49));
  NAND2XL g2408__6417(.A (n_102), .B (n_88), .Y (n_46));
  NAND2BXL g2371__5477(.AN (n_44), .B (n_43), .Y (n_45));
  NAND2XL g2379__2398(.A (state[1]), .B (n_88), .Y (n_42));
  OAI2BB1X1 g2416__5107(.A0N (address_reg[6]), .A1N (n_96), .B0 (n_16),
       .Y (n_41));
  NOR2XL g2405__6260(.A (n_24), .B (n_40), .Y (n_100));
  NAND2XL g2361__4319(.A (n_40), .B (n_51), .Y (n_39));
  AOI22XL g2350__8428(.A0 (n_37), .A1 (n_25), .B0 (n_63), .B1 (n_73),
       .Y (n_38));
  INVXL g2365(.A (n_122), .Y (n_36));
  OAI21XL g2356__5526(.A0 (state[2]), .A1 (n_14), .B0 (n_35), .Y
       (n_80));
  NOR2XL g2377__6783(.A (n_33), .B (n_31), .Y (n_34));
  NOR2XL g2378__1617(.A (n_29), .B (n_31), .Y (n_30));
  NAND2XL g2390__2802(.A (enable), .B (n_26), .Y (n_47));
  NAND2BXL g2370__1705(.AN (n_28), .B (n_57), .Y (n_122));
  NOR3XL g2313__5122(.A (state[0]), .B (n_23), .C (n_37), .Y (ready));
  AOI222X1 g2407__8246(.A0 (write_data_reg[6]), .A1 (n_96), .B0
       (write_data_reg[2]), .B1 (n_93), .C0 (write_data_reg[4]), .C1
       (n_91), .Y (n_27));
  NOR2XL g2364__7098(.A (state[0]), .B (n_26), .Y (n_85));
  NOR2XL g2362__6131(.A (state[3]), .B (n_25), .Y (n_86));
  NOR2BX1 g2404__1881(.AN (n_73), .B (n_24), .Y (n_92));
  OR2X1 g2357__5115(.A (n_23), .B (n_22), .Y (n_84));
  NAND2XL g2385__7482(.A (n_93), .B (n_19), .Y (n_21));
  NAND2XL g2382__4733(.A (n_96), .B (n_19), .Y (n_20));
  NAND2XL g2374__6161(.A (n_101), .B (n_19), .Y (n_18));
  NAND2XL g2388__9315(.A (n_91), .B (n_19), .Y (n_17));
  NOR2XL g2391__9945(.A (state[0]), .B (i2c_sda), .Y (n_43));
  AOI22XL g2421__2883(.A0 (address_reg[2]), .A1 (n_93), .B0
       (address_reg[4]), .B1 (n_91), .Y (n_16));
  DFFNSRX1 scl_enable_reg(.RN (n_125), .SN (1'b1), .CKN (i2c_clk), .D
       (n_7), .Q (scl_enable), .QN (UNCONNECTED1));
  INVXL g2406(.A (n_72), .Y (n_50));
  INVXL g2415(.A (n_102), .Y (n_40));
  INVXL g2410(.A (n_15), .Y (n_88));
  DFFSHQX1 i2c_clk_reg(.SN (n_125), .CK (clk), .D (n_8), .Q (i2c_clk));
  AND2X1 g2373__2346(.A (n_11), .B (n_67), .Y (n_14));
  OAI21XL g2381__1666(.A0 (n_63), .A1 (n_101), .B0 (n_24), .Y (n_25));
  NAND2XL g2383__7410(.A (n_35), .B (n_37), .Y (n_28));
  NOR2XL g2384__6417(.A (state[0]), .B (n_10), .Y (n_61));
  INVXL g2403(.A (i2c_sda), .Y (n_26));
  NAND2XL g2393__5477(.A (state[1]), .B (n_57), .Y (n_31));
  NAND2XL g2343__2398(.A (state[2]), .B (n_12), .Y (n_13));
  NAND2XL g2413__5107(.A (n_101), .B (n_57), .Y (n_15));
  NAND2XL g2363__6260(.A (n_11), .B (n_9), .Y (n_22));
  NOR2XL g2409__4319(.A (n_63), .B (n_37), .Y (n_72));
  NOR2XL g2417__8428(.A (state[3]), .B (n_10), .Y (n_102));
  NOR2XL g2418__5526(.A (state[3]), .B (n_44), .Y (n_73));
  NAND2XL g2355__6783(.A (state[2]), .B (n_35), .Y (n_113));
  NAND3XL g2386__3680(.A (state[1]), .B (n_66), .C (n_63), .Y (n_48));
  INVXL g2389(.A (n_35), .Y (n_23));
  NAND2XL g2375__1617(.A (state[3]), .B (n_9), .Y (n_51));
  NOR2XL g2394__2802(.A (n_67), .B (n_24), .Y (n_19));
  OAI22XL g2323__1705(.A0 (i2c_clk), .A1 (n_5), .B0 (clk_counter[0]),
       .B1 (n_3), .Y (n_8));
  OAI2BB1X1 g2309__5122(.A0N (state[3]), .A1N (n_63), .B0 (n_9), .Y
       (n_7));
  INVXL g2428(.A (n_91), .Y (n_33));
  NAND2XL g2372__8246(.A (state[2]), .B (n_66), .Y (n_4));
  NAND2XL g2360__7098(.A (scl_enable), .B (n_3), .Y (i2c_scl));
  NAND2XL g2387__6131(.A (state[0]), .B (n_67), .Y (n_12));
  AND2X1 g2392__1881(.A (n_63), .B (enable), .Y (n_11));
  NAND2XL g2422__5115(.A (state[1]), .B (n_2), .Y (n_10));
  NAND2XL g2423__7482(.A (state[2]), .B (n_67), .Y (n_44));
  NAND2XL g2344__4733(.A (counter[0]), .B (n_63), .Y (n_1));
  NOR2XL g2419__6161(.A (counter[0]), .B (n_63), .Y (n_57));
  INVXL g2411(.A (n_9), .Y (n_37));
  NOR2XL g2395__9315(.A (rst), .B (state[3]), .Y (n_35));
  INVXL g2424(.A (n_29), .Y (n_96));
  AND2X1 g2427__9945(.A (n_0), .B (counter[1]), .Y (n_93));
  NOR2XL g2429__2883(.A (counter[1]), .B (n_0), .Y (n_91));
  TBUFX1 g3__2346(.A (sda_out), .OE (sda_drive_en), .Y (i2c_sda));
  NOR2XL g2420__1666(.A (counter[1]), .B (counter[2]), .Y (n_101));
  INVXL g2402(.A (rst), .Y (n_125));
  NAND2XL g2425__7410(.A (counter[1]), .B (counter[2]), .Y (n_29));
  NAND2XL g2412__6417(.A (counter[0]), .B (state[0]), .Y (n_24));
  NOR2XL g2414__5477(.A (state[1]), .B (state[2]), .Y (n_9));
  INVXL g2431(.A (i2c_clk), .Y (n_3));
  INVXL g2433(.A (counter[2]), .Y (n_0));
  DFFRX1 \clk_counter_reg[0] (.RN (n_125), .CK (clk), .D (n_5), .Q
       (clk_counter[0]), .QN (n_5));
  DFFRX1 \state_reg[2] (.RN (n_125), .CK (i2c_clk), .D (n_87), .Q
       (state[2]), .QN (n_2));
  DFFRX1 \state_reg[3] (.RN (n_125), .CK (i2c_clk), .D (n_119), .Q
       (state[3]), .QN (n_66));
  DFFRX1 \state_reg[1] (.RN (n_125), .CK (i2c_clk), .D (n_110), .Q
       (state[1]), .QN (n_67));
  DFFRX1 \state_reg[0] (.RN (n_125), .CK (i2c_clk), .D (n_116), .Q
       (state[0]), .QN (n_63));
  NOR2BX1 g2(.AN (n_93), .B (n_31), .Y (n_152));
endmodule

