
// Generated by Cadence Genus(TM) Synthesis Solution 22.16-s078_1
// Generated on: Mar  6 2026 18:18:24 -03 (Mar  6 2026 21:18:24 UTC)

// Verification Directory fv/i2c_slave_controller 

module i2c_slave_controller(sda, scl, rst, data_received, data_to_send);
  input scl, rst;
  input [7:0] data_to_send;
  output [7:0] data_received;
  inout sda;
  wire scl, rst;
  wire [7:0] data_to_send;
  wire [7:0] data_received;
  wire sda;
  wire [3:0] counter;
  wire [7:0] address_reg;
  wire [2:0] state;
  wire UNCONNECTED, UNCONNECTED0, n_0, n_1, n_2, n_3, n_5, n_6;
  wire n_7, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_17, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_67, n_68, n_69, n_70, n_71, n_72, n_73, n_74;
  wire n_75, n_76, n_77, n_78, n_79, n_80, n_81, n_82;
  wire n_83, n_84, n_85, n_86, n_87, n_88, n_89, n_91;
  wire n_92, n_93, n_95, n_96, n_97, n_98, n_99, n_100;
  wire n_101, n_102, n_114, n_115, n_116, n_117, sda_drive_en, sda_out;
  wire start_event;
  DFFNSRX1 sda_out_reg(.RN (1'b1), .SN (n_102), .CKN (scl), .D (n_99),
       .Q (sda_out), .QN (UNCONNECTED));
  DFFRHQX1 \counter_reg[1] (.RN (n_102), .CK (scl), .D (n_98), .Q
       (counter[1]));
  DFFRHQX1 \counter_reg[0] (.RN (n_102), .CK (scl), .D (n_100), .Q
       (counter[0]));
  OAI211X1 g1998__2398(.A0 (n_69), .A1 (n_92), .B0 (n_87), .C0 (n_88),
       .Y (n_101));
  OAI211X1 g2003__5107(.A0 (n_70), .A1 (n_97), .B0 (n_115), .C0 (n_96),
       .Y (n_100));
  MX2X1 g1992__6260(.A (n_91), .B (sda_out), .S0 (n_89), .Y (n_99));
  OAI211X1 g2004__4319(.A0 (n_31), .A1 (n_97), .B0 (n_36), .C0 (n_96),
       .Y (n_98));
  OAI211X1 g2005__8428(.A0 (n_2), .A1 (n_28), .B0 (n_33), .C0 (n_96),
       .Y (n_95));
  DFFNSRX1 sda_drive_en_reg(.RN (n_102), .SN (1'b1), .CKN (scl), .D
       (n_114), .Q (sda_drive_en), .QN (n_0));
  NAND3BXL g1991__5526(.AN (n_85), .B (n_92), .C (n_24), .Y (n_93));
  DFFRHQX1 \address_reg_reg[2] (.RN (n_102), .CK (scl), .D (n_75), .Q
       (address_reg[2]));
  DFFRHQX1 \address_reg_reg[3] (.RN (n_102), .CK (scl), .D (n_73), .Q
       (address_reg[3]));
  DFFRHQX1 \address_reg_reg[4] (.RN (n_102), .CK (scl), .D (n_80), .Q
       (address_reg[4]));
  DFFRHQX1 \address_reg_reg[5] (.RN (n_102), .CK (scl), .D (n_81), .Q
       (address_reg[5]));
  DFFRHQX1 \address_reg_reg[7] (.RN (n_102), .CK (scl), .D (n_77), .Q
       (address_reg[7]));
  DFFRHQX1 \address_reg_reg[0] (.RN (n_102), .CK (scl), .D (n_76), .Q
       (address_reg[0]));
  NAND3XL g2035__6783(.A (n_51), .B (n_72), .C (n_59), .Y (n_91));
  NOR2XL g2014__1617(.A (n_56), .B (n_86), .Y (n_88));
  AOI2BB1XL g2039__2802(.A0N (state[1]), .A1N (n_87), .B0 (n_86), .Y
       (n_96));
  DFFRHQX1 \address_reg_reg[6] (.RN (n_102), .CK (scl), .D (n_74), .Q
       (address_reg[6]));
  DFFRHQX1 \address_reg_reg[1] (.RN (n_102), .CK (scl), .D (n_78), .Q
       (address_reg[1]));
  OAI32X1 g2016__1705(.A0 (address_reg[0]), .A1 (state[0]), .A2 (n_83),
       .B0 (n_13), .B1 (n_82), .Y (n_85));
  OAI221X1 g1994__5122(.A0 (n_5), .A1 (n_83), .B0 (n_71), .B1 (n_82),
       .C0 (n_57), .Y (n_84));
  OAI21XL g1997__8246(.A0 (n_79), .A1 (n_45), .B0 (n_65), .Y (n_81));
  OAI21XL g1995__7098(.A0 (n_79), .A1 (n_52), .B0 (n_67), .Y (n_80));
  OAI21XL g1996__6131(.A0 (n_79), .A1 (n_27), .B0 (n_62), .Y (n_78));
  OAI21XL g1999__1881(.A0 (n_79), .A1 (n_47), .B0 (n_61), .Y (n_77));
  OAI21XL g1990__5115(.A0 (n_79), .A1 (n_48), .B0 (n_63), .Y (n_76));
  OAI21XL g2000__7482(.A0 (n_79), .A1 (n_53), .B0 (n_60), .Y (n_75));
  OAI21XL g2002__4733(.A0 (n_79), .A1 (n_26), .B0 (n_64), .Y (n_74));
  OAI21XL g1993__6161(.A0 (n_79), .A1 (n_46), .B0 (n_68), .Y (n_73));
  AOI211XL g2048__9315(.A0 (n_38), .A1 (n_83), .B0 (state[0]), .C0
       (state[2]), .Y (n_86));
  SDFFRHQX1 \data_received_reg[7] (.RN (n_102), .CK (scl), .D (sda),
       .SI (data_received[7]), .SE (n_50), .Q (data_received[7]));
  SDFFRHQX1 \data_received_reg[1] (.RN (n_102), .CK (scl), .D (sda),
       .SI (data_received[1]), .SE (n_37), .Q (data_received[1]));
  SDFFRHQX1 \data_received_reg[3] (.RN (n_102), .CK (scl), .D (sda),
       .SI (data_received[3]), .SE (n_44), .Q (data_received[3]));
  AOI33XL g2047__9945(.A0 (1'b1), .A1 (n_20), .A2 (n_39), .B0 (n_70),
       .B1 (data_to_send[1]), .B2 (n_58), .Y (n_72));
  AOI32X1 g2038__2883(.A0 (n_69), .A1 (n_15), .A2 (n_54), .B0
       (state[2]), .B1 (n_71), .Y (n_89));
  SDFFRHQX1 \data_received_reg[5] (.RN (n_102), .CK (scl), .D (sda),
       .SI (data_received[5]), .SE (n_41), .Q (data_received[5]));
  NAND2XL g2006__2346(.A (address_reg[3]), .B (n_116), .Y (n_68));
  NAND2XL g2007__1666(.A (address_reg[4]), .B (n_116), .Y (n_67));
  SDFFRHQX1 \data_received_reg[4] (.RN (n_102), .CK (scl), .D
       (data_received[4]), .SI (sda), .SE (n_32), .Q
       (data_received[4]));
  SDFFRHQX1 \data_received_reg[2] (.RN (n_102), .CK (scl), .D
       (data_received[2]), .SI (sda), .SE (n_29), .Q
       (data_received[2]));
  SDFFRHQX1 \data_received_reg[6] (.RN (n_102), .CK (scl), .D
       (data_received[6]), .SI (sda), .SE (n_34), .Q
       (data_received[6]));
  SDFFRHQX1 \data_received_reg[0] (.RN (n_102), .CK (scl), .D
       (data_received[0]), .SI (sda), .SE (n_35), .Q
       (data_received[0]));
  NAND2XL g2008__7410(.A (address_reg[5]), .B (n_116), .Y (n_65));
  NAND2XL g2009__6417(.A (address_reg[6]), .B (n_116), .Y (n_64));
  NAND2XL g2010__5477(.A (address_reg[0]), .B (n_116), .Y (n_63));
  NAND2XL g2011__2398(.A (address_reg[1]), .B (n_116), .Y (n_62));
  NAND2XL g2012__5107(.A (address_reg[7]), .B (n_116), .Y (n_61));
  NAND2XL g2013__6260(.A (address_reg[2]), .B (n_116), .Y (n_60));
  AOI33XL g2058__4319(.A0 (data_to_send[0]), .A1 (1'b1), .A2 (n_19),
       .B0 (n_40), .B1 (data_to_send[5]), .B2 (n_58), .Y (n_59));
  AOI31X1 g2015__8428(.A0 (state[2]), .A1 (start_event), .A2 (n_56),
       .B0 (n_55), .Y (n_57));
  NAND2XL g2065__5526(.A (state[1]), .B (n_54), .Y (n_83));
  MXI2XL g2031__6783(.A (address_reg[2]), .B (sda), .S0 (n_23), .Y
       (n_53));
  MXI2XL g2037__3680(.A (address_reg[4]), .B (sda), .S0 (n_17), .Y
       (n_52));
  AOI33XL g2059__2802(.A0 (data_to_send[3]), .A1 (n_43), .A2 (n_58),
       .B0 (n_49), .B1 (data_to_send[7]), .B2 (n_58), .Y (n_51));
  NAND2XL g2024__1705(.A (n_49), .B (n_42), .Y (n_50));
  MXI2XL g2032__5122(.A (address_reg[0]), .B (sda), .S0 (n_117), .Y
       (n_48));
  MXI2XL g2033__8246(.A (sda), .B (address_reg[7]), .S0 (n_12), .Y
       (n_47));
  MXI2XL g2034__7098(.A (sda), .B (address_reg[3]), .S0 (n_10), .Y
       (n_46));
  MXI2XL g2029__6131(.A (sda), .B (address_reg[5]), .S0 (n_11), .Y
       (n_45));
  NAND2XL g2022__1881(.A (n_43), .B (n_42), .Y (n_44));
  NAND2XL g2021__5115(.A (n_40), .B (n_42), .Y (n_41));
  INVXL g2067(.A (n_25), .Y (n_39));
  OR2X1 g2068__7482(.A (state[1]), .B (start_event), .Y (n_38));
  NAND2XL g2020__4733(.A (n_70), .B (n_42), .Y (n_37));
  NAND2XL g2018__6161(.A (counter[1]), .B (n_97), .Y (n_36));
  NAND3BXL g2061__9315(.AN (start_event), .B (state[0]), .C (state[2]),
       .Y (n_87));
  NOR4BX1 g2071__9945(.AN (address_reg[4]), .B (address_reg[3]), .C
       (address_reg[7]), .D (n_9), .Y (n_54));
  NOR2XL g2026__2883(.A (n_21), .B (n_82), .Y (n_35));
  NOR2XL g2025__2346(.A (n_33), .B (n_30), .Y (n_34));
  NOR2XL g2023__1666(.A (n_31), .B (n_30), .Y (n_32));
  NOR2XL g2027__7410(.A (n_22), .B (n_30), .Y (n_29));
  INVXL g2042(.A (n_97), .Y (n_28));
  MXI2XL g2036__6417(.A (sda), .B (address_reg[1]), .S0 (n_7), .Y
       (n_27));
  MXI2XL g2030__5477(.A (address_reg[6]), .B (sda), .S0 (n_6), .Y
       (n_26));
  AOI222X1 g2069__2398(.A0 (data_to_send[2]), .A1 (n_43), .B0
       (data_to_send[6]), .B1 (n_49), .C0 (data_to_send[4]), .C1
       (n_40), .Y (n_25));
  NAND2XL g2019__5107(.A (state[1]), .B (n_56), .Y (n_24));
  NOR2XL g2060__6260(.A (counter[0]), .B (n_22), .Y (n_23));
  NOR2XL g2046__4319(.A (n_14), .B (n_21), .Y (n_42));
  NAND2XL g2045__8428(.A (n_92), .B (n_20), .Y (n_97));
  INVXL g2075(.A (n_82), .Y (n_19));
  NOR2XL g2062__6783(.A (counter[0]), .B (n_31), .Y (n_17));
  DFFNSRX1 start_event_reg(.RN (n_102), .SN (1'b1), .CKN (sda), .D
       (scl), .Q (UNCONNECTED0), .QN (start_event));
  NAND2XL g2049__1617(.A (n_20), .B (n_15), .Y (n_30));
  OAI21XL g2050__2802(.A0 (n_69), .A1 (n_70), .B0 (n_14), .Y (n_56));
  OR2X1 g2028__1705(.A (n_69), .B (n_13), .Y (n_79));
  NAND2XL g2063__5122(.A (counter[0]), .B (n_49), .Y (n_12));
  NAND2XL g2056__8246(.A (counter[0]), .B (n_40), .Y (n_11));
  NAND2XL g2055__7098(.A (counter[0]), .B (n_43), .Y (n_10));
  NAND3XL g2085__6131(.A (address_reg[2]), .B (address_reg[6]), .C
       (n_1), .Y (n_9));
  NAND2XL g2076__1881(.A (n_20), .B (n_70), .Y (n_82));
  NAND2XL g2053__5115(.A (counter[0]), .B (n_70), .Y (n_7));
  NOR2XL g2054__7482(.A (counter[0]), .B (n_33), .Y (n_6));
  INVXL g2051(.A (n_55), .Y (n_92));
  INVXL g2064(.A (n_15), .Y (n_21));
  INVXL g2077(.A (n_43), .Y (n_22));
  INVXL g2072(.A (n_40), .Y (n_31));
  NAND2XL g2043__4733(.A (address_reg[0]), .B (n_69), .Y (n_5));
  NOR2XL g2066__6161(.A (state[2]), .B (n_71), .Y (n_15));
  NAND2XL g2044__9315(.A (n_71), .B (n_3), .Y (n_13));
  INVXL g2078(.A (n_33), .Y (n_49));
  NOR2XL g2057__9945(.A (n_71), .B (n_3), .Y (n_55));
  NOR2XL g2083__2883(.A (counter[0]), .B (n_69), .Y (n_20));
  AND2X1 g2079__2346(.A (n_2), .B (counter[1]), .Y (n_43));
  NOR2XL g2074__1666(.A (counter[1]), .B (n_2), .Y (n_40));
  TBUFXL g1__7410(.A (sda_out), .OE (sda_drive_en), .Y (sda));
  NAND2XL g2080__6417(.A (counter[1]), .B (counter[2]), .Y (n_33));
  NOR2XL g2084__5477(.A (counter[1]), .B (counter[2]), .Y (n_70));
  NOR2XL g2086__2398(.A (address_reg[1]), .B (address_reg[5]), .Y
       (n_1));
  NAND2XL g2082__5107(.A (counter[0]), .B (state[0]), .Y (n_14));
  INVXL g2092(.A (rst), .Y (n_102));
  INVXL g2118(.A (n_14), .Y (n_58));
  OAI21XL g2(.A0 (n_0), .A1 (n_92), .B0 (n_89), .Y (n_114));
  OAI21X1 g2119(.A0 (n_55), .A1 (n_69), .B0 (counter[0]), .Y (n_115));
  DFFRX1 \state_reg[1] (.RN (n_102), .CK (scl), .D (n_93), .Q
       (state[1]), .QN (n_71));
  DFFRX1 \state_reg[0] (.RN (n_102), .CK (scl), .D (n_101), .Q
       (state[0]), .QN (n_69));
  DFFRX1 \state_reg[2] (.RN (n_102), .CK (scl), .D (n_84), .Q
       (state[2]), .QN (n_3));
  DFFRX1 \counter_reg[2] (.RN (n_102), .CK (scl), .D (n_95), .Q
       (counter[2]), .QN (n_2));
  AO21X1 g2128(.A0 (n_69), .A1 (start_event), .B0 (n_13), .Y (n_116));
  NOR2BX1 g2129(.AN (n_70), .B (counter[0]), .Y (n_117));
endmodule

