
// Generated by Cadence Genus(TM) Synthesis Solution 22.16-s078_1
// Generated on: Mar  5 2026 18:57:06 -03 (Mar  5 2026 21:57:06 UTC)

// Verification Directory fv/i2c_slave_controller 

module i2c_slave_controller(sda, scl, rst, data_received, data_to_send);
  input scl, rst;
  input [7:0] data_to_send;
  output [7:0] data_received;
  inout sda;
  wire scl, rst;
  wire [7:0] data_to_send;
  wire [7:0] data_received;
  wire sda;
  wire [3:0] counter;
  wire [2:0] state;
  wire [7:0] address_reg;
  wire UNCONNECTED, n_0, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_12, n_16, n_17, n_18, n_19, n_20;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_98, n_99, n_102, n_103, n_104, n_105, n_106, n_107;
  wire n_108, n_109, n_110, n_111, n_112, n_115, n_116, n_117;
  wire n_118, n_119, n_120, n_121, n_122, n_123, n_124, n_125;
  wire n_126, n_127, n_128, n_129, n_130, n_131, n_132, n_133;
  wire n_134, n_135, n_136, n_137, n_138, n_150, n_151, n_152;
  wire n_153, n_154, n_155, sda_drive_en, start_event, stop_event;
  assign address_reg[5] = 1'b0;
  assign address_reg[3] = 1'b0;
  assign address_reg[4] = 1'b0;
  assign address_reg[6] = 1'b0;
  assign address_reg[2] = 1'b0;
  assign address_reg[1] = 1'b0;
  assign address_reg[7] = 1'b0;
  assign address_reg[0] = 1'b0;
  assign state[1] = 1'b0;
  assign state[2] = 1'b0;
  assign counter[3] = 1'b0;
  assign counter[0] = 1'b1;
  assign counter[1] = 1'b1;
  assign counter[2] = 1'b1;
  INVXL g2241(.A (rst), .Y (n_138));
  DFFRHQX1 \counter_reg[2]120 (.RN (n_138), .CK (scl), .D (n_137), .Q
       (counter[2]));
  DFFRHQX1 \counter_reg[1]119 (.RN (n_138), .CK (scl), .D (n_136), .Q
       (counter[1]));
  DFFRHQX1 \counter_reg[0]118 (.RN (n_138), .CK (scl), .D (n_133), .Q
       (counter[0]));
  DFFRHQX1 \counter_reg[3]121 (.RN (n_138), .CK (scl), .D (n_131), .Q
       (counter[3]));
  OAI221X1 g2338__2398(.A0 (n_48), .A1 (n_132), .B0 (n_65), .B1
       (n_135), .C0 (n_134), .Y (n_137));
  OAI211X1 g2339__5107(.A0 (n_33), .A1 (n_135), .B0 (n_134), .C0
       (n_130), .Y (n_136));
  OAI221X1 g2340__6260(.A0 (counter[0]), .A1 (n_132), .B0 (n_34), .B1
       (n_135), .C0 (n_134), .Y (n_133));
  OAI22XL g2343__4319(.A0 (n_57), .A1 (n_132), .B0 (n_12), .B1 (n_135),
       .Y (n_131));
  DFFRHQX1 \state_reg[2]95 (.RN (n_138), .CK (scl), .D (n_128), .Q
       (state[2]));
  DFFRHQX1 \state_reg[0]93 (.RN (n_138), .CK (scl), .D (n_129), .Q
       (state[0]));
  OAI2BB1X1 g2355__8428(.A0N (n_47), .A1N (n_19), .B0 (n_126), .Y
       (n_130));
  DFFRHQX1 \state_reg[1]94 (.RN (n_138), .CK (scl), .D (n_125), .Q
       (state[1]));
  OAI21XL g2330__5526(.A0 (n_18), .A1 (n_127), .B0 (n_134), .Y (n_129));
  OAI211X1 g2341__6783(.A0 (n_17), .A1 (n_127), .B0 (n_121), .C0
       (n_123), .Y (n_128));
  INVXL g2380(.A (n_126), .Y (n_132));
  OAI221X1 g2336__3680(.A0 (n_16), .A1 (n_127), .B0 (address_reg[0]),
       .B1 (n_124), .C0 (n_116), .Y (n_125));
  OAI211X1 g2383__1617(.A0 (n_98), .A1 (n_119), .B0 (n_122), .C0
       (n_117), .Y (n_126));
  AND3XL g2349__2802(.A (n_155), .B (n_124), .C (n_87), .Y (n_134));
  NAND2BXL g2356__1705(.AN (n_124), .B (address_reg[0]), .Y (n_123));
  NAND3BXL g2388__5122(.AN (n_111), .B (n_2), .C (n_135), .Y (n_122));
  DFFRHQX1 \address_reg_reg[0]102 (.RN (n_138), .CK (scl), .D (n_118),
       .Q (address_reg[0]));
  NAND2XL g2382__8246(.A (n_106), .B (n_135), .Y (n_124));
  NAND2XL g2365__7098(.A (n_120), .B (n_153), .Y (n_127));
  DFFNSRX1 sda_drive_en_reg(.RN (n_138), .SN (1'b1), .CKN (scl), .D
       (n_112), .Q (sda_drive_en), .QN (UNCONNECTED));
  DFFRHQX1 \address_reg_reg[7]109 (.RN (n_138), .CK (scl), .D (n_105),
       .Q (address_reg[7]));
  DFFRHQX1 \address_reg_reg[1]103 (.RN (n_138), .CK (scl), .D (n_107),
       .Q (address_reg[1]));
  DFFRHQX1 \address_reg_reg[2]104 (.RN (n_138), .CK (scl), .D (n_102),
       .Q (address_reg[2]));
  INVXL g2411(.A (n_119), .Y (n_135));
  DFFRHQX1 \address_reg_reg[6]108 (.RN (n_138), .CK (scl), .D (n_104),
       .Q (address_reg[6]));
  DFFRHQX1 \address_reg_reg[4]106 (.RN (n_138), .CK (scl), .D (n_110),
       .Q (address_reg[4]));
  DFFRHQX1 \address_reg_reg[3]105 (.RN (n_138), .CK (scl), .D (n_103),
       .Q (address_reg[3]));
  DFFRHQX1 \address_reg_reg[5]107 (.RN (n_138), .CK (scl), .D (n_108),
       .Q (address_reg[5]));
  OAI222XL g2342__6131(.A0 (n_115), .A1 (n_117), .B0 (n_116), .B1
       (n_8), .C0 (n_115), .C1 (n_109), .Y (n_118));
  OAI211X1 g2335__1881(.A0 (n_111), .A1 (n_95), .B0 (n_91), .C0 (n_49),
       .Y (n_112));
  OAI31X1 g2412__5115(.A0 (n_150), .A1 (n_96), .A2 (n_82), .B0 (n_120),
       .Y (n_119));
  OAI211X1 g2329__7482(.A0 (n_55), .A1 (n_109), .B0 (n_77), .C0 (n_85),
       .Y (n_110));
  OAI211X1 g2328__4733(.A0 (n_5), .A1 (n_109), .B0 (n_72), .C0 (n_83),
       .Y (n_108));
  OAI211X1 g2344__6161(.A0 (n_23), .A1 (n_109), .B0 (n_75), .C0 (n_86),
       .Y (n_107));
  OAI211X1 g2334__9945(.A0 (n_6), .A1 (n_109), .B0 (n_76), .C0 (n_94),
       .Y (n_105));
  OAI211X1 g2333__2883(.A0 (n_7), .A1 (n_109), .B0 (n_78), .C0 (n_93),
       .Y (n_104));
  OAI211X1 g2331__2346(.A0 (n_4), .A1 (n_109), .B0 (n_73), .C0 (n_89),
       .Y (n_103));
  OAI211X1 g2337__1666(.A0 (n_3), .A1 (n_109), .B0 (n_74), .C0 (n_80),
       .Y (n_102));
  SDFFRHQX1 \data_received_reg[7] (.RN (n_138), .CK (scl), .D
       (data_received[7]), .SI (sda), .SE (n_62), .Q
       (data_received[7]));
  SDFFRHQX1 \data_received_reg[5] (.RN (n_138), .CK (scl), .D
       (data_received[5]), .SI (sda), .SE (n_68), .Q
       (data_received[5]));
  SDFFRHQX1 \data_received_reg[0] (.RN (n_138), .CK (scl), .D
       (data_received[0]), .SI (sda), .SE (n_154), .Q
       (data_received[0]));
  SDFFRHQX1 \data_received_reg[6] (.RN (n_138), .CK (scl), .D
       (data_received[6]), .SI (sda), .SE (n_59), .Q
       (data_received[6]));
  DFFRHQX1 stop_event_reg(.RN (n_138), .CK (sda), .D (n_79), .Q
       (stop_event));
  NAND2XL g2394__6417(.A (n_96), .B (n_109), .Y (n_117));
  SDFFRHQX1 \data_received_reg[4] (.RN (n_138), .CK (scl), .D
       (data_received[4]), .SI (sda), .SE (n_42), .Q
       (data_received[4]));
  NAND4XL g2381__5477(.A (n_66), .B (n_52), .C (n_53), .D (n_38), .Y
       (n_95));
  SDFFRHQX1 \data_received_reg[1] (.RN (n_138), .CK (scl), .D
       (data_received[1]), .SI (sda), .SE (n_44), .Q
       (data_received[1]));
  SDFFRHQX1 \data_received_reg[3] (.RN (n_138), .CK (scl), .D
       (data_received[3]), .SI (sda), .SE (n_51), .Q
       (data_received[3]));
  SDFFRHQX1 \data_received_reg[2] (.RN (n_138), .CK (scl), .D
       (data_received[2]), .SI (sda), .SE (n_46), .Q
       (data_received[2]));
  NAND4XL g2345__2398(.A (n_60), .B (n_92), .C (sda), .D (n_109), .Y
       (n_94));
  NAND4XL g2346__5107(.A (n_58), .B (n_92), .C (sda), .D (n_109), .Y
       (n_93));
  NOR2XL g2347__6260(.A (n_81), .B (n_90), .Y (n_91));
  NAND4XL g2348__4319(.A (n_50), .B (n_92), .C (sda), .D (n_109), .Y
       (n_89));
  NAND4XL g2350__8428(.A (n_43), .B (n_92), .C (sda), .D (n_109), .Y
       (n_86));
  NAND4XL g2351__5526(.A (n_41), .B (n_92), .C (sda), .D (n_109), .Y
       (n_85));
  OAI211X1 g2419__6783(.A0 (n_69), .A1 (n_111), .B0 (n_155), .C0
       (1'b1), .Y (n_84));
  NAND4XL g2352__3680(.A (n_67), .B (n_92), .C (sda), .D (n_109), .Y
       (n_83));
  NAND2BXL g2422__1617(.AN (n_81), .B (n_87), .Y (n_82));
  NAND4XL g2353__2802(.A (n_45), .B (n_92), .C (sda), .D (n_109), .Y
       (n_80));
  NOR2XL g2332__1705(.A (start_event), .B (n_64), .Y (n_79));
  NAND4XL g2374__5122(.A (n_39), .B (address_reg[6]), .C (n_92), .D
       (1'b1), .Y (n_78));
  NAND4XL g2367__8246(.A (n_31), .B (address_reg[4]), .C (n_92), .D
       (1'b1), .Y (n_77));
  NAND4XL g2368__7098(.A (n_40), .B (address_reg[7]), .C (n_92), .D
       (1'b1), .Y (n_76));
  NAND4XL g2369__6131(.A (n_36), .B (address_reg[1]), .C (n_92), .D
       (1'b1), .Y (n_75));
  NAND4XL g2370__1881(.A (n_35), .B (address_reg[2]), .C (n_92), .D
       (1'b1), .Y (n_74));
  NAND4XL g2371__5115(.A (n_30), .B (address_reg[3]), .C (n_92), .D
       (1'b1), .Y (n_73));
  NAND4XL g2373__7482(.A (n_54), .B (address_reg[5]), .C (n_92), .D
       (1'b1), .Y (n_72));
  NAND2XL g2362__4733(.A (n_71), .B (n_109), .Y (n_116));
  NOR2XL g2425__6161(.A (n_99), .B (n_63), .Y (n_96));
  NOR2XL g2421__9315(.A (n_69), .B (n_98), .Y (n_70));
  AND2X1 g2357__9945(.A (n_61), .B (n_67), .Y (n_68));
  AOI32X1 g2404__2883(.A0 (n_65), .A1 (n_151), .A2 (data_to_send[1]),
       .B0 (n_56), .B1 (data_to_send[0]), .Y (n_66));
  MXI2XL g2354__2346(.A (stop_event), .B (scl), .S0 (n_26), .Y (n_64));
  NOR2XL g2418__1666(.A (n_69), .B (n_63), .Y (n_71));
  AND2X1 g2360__7410(.A (n_61), .B (n_60), .Y (n_62));
  AND2X1 g2359__6417(.A (n_61), .B (n_58), .Y (n_59));
  XNOR2X1 g2376__5477(.A (counter[3]), .B (n_56), .Y (n_57));
  NOR4X1 g2429__2398(.A (address_reg[5]), .B (n_55), .C (n_24), .D
       (n_20), .Y (n_81));
  INVXL g2401(.A (n_67), .Y (n_54));
  AOI33XL g2403__6260(.A0 (n_28), .A1 (counter[2]), .A2
       (data_to_send[4]), .B0 (n_151), .B1 (counter[2]), .B2
       (data_to_send[5]), .Y (n_53));
  AOI33XL g2402__4319(.A0 (n_65), .A1 (n_152), .A2 (data_to_send[2]),
       .B0 (n_65), .B1 (n_37), .B2 (data_to_send[3]), .Y (n_52));
  AND2X1 g2358__8428(.A (n_61), .B (n_50), .Y (n_51));
  INVXL g2441(.A (n_69), .Y (n_99));
  OAI2BB1X2 g2413__6783(.A0N (n_120), .A1N (n_92), .B0 (n_87), .Y
       (n_109));
  NAND4BXL g2372__3680(.AN (1'b0), .B (state[2]), .C (n_111), .D
       (sda_drive_en), .Y (n_49));
  AOI21XL g2456__1617(.A0 (n_47), .A1 (counter[2]), .B0 (n_56), .Y
       (n_48));
  AND2X1 g2363__2802(.A (n_61), .B (n_45), .Y (n_46));
  AND2X1 g2364__1705(.A (n_61), .B (n_43), .Y (n_44));
  AND2X1 g2361__5122(.A (n_61), .B (n_41), .Y (n_42));
  INVXL g2390(.A (n_60), .Y (n_40));
  INVXL g2391(.A (n_58), .Y (n_39));
  AOI33XL g2393__8246(.A0 (counter[2]), .A1 (n_152), .A2
       (data_to_send[6]), .B0 (counter[2]), .B1 (n_37), .B2
       (data_to_send[7]), .Y (n_38));
  INVXL g2399(.A (n_43), .Y (n_36));
  INVXL g2400(.A (n_45), .Y (n_35));
  NOR3XL g2396__7098(.A (n_34), .B (n_33), .C (n_32), .Y (n_60));
  NOR3XL g2397__6131(.A (counter[0]), .B (n_33), .C (n_32), .Y (n_58));
  INVXL g2384(.A (n_41), .Y (n_31));
  INVXL g2389(.A (n_50), .Y (n_30));
  NOR3XL g2408__1881(.A (counter[1]), .B (n_34), .C (n_32), .Y (n_67));
  NAND2XL g2442__5115(.A (n_28), .B (n_27), .Y (n_69));
  INVXL g2434(.A (n_92), .Y (n_63));
  NOR2XL g2457__7482(.A (n_47), .B (counter[2]), .Y (n_56));
  AND3XL g2395__4733(.A (counter[0]), .B (counter[1]), .C (n_27), .Y
       (n_50));
  AND3XL g2406__6161(.A (n_33), .B (counter[0]), .C (n_27), .Y (n_43));
  AND3XL g2407__9315(.A (n_34), .B (counter[1]), .C (n_27), .Y (n_45));
  NAND2XL g2426__9945(.A (start_event), .B (n_25), .Y (n_87));
  NAND2XL g2378__2883(.A (scl), .B (n_25), .Y (n_26));
  NAND4XL g2437__2346(.A (n_23), .B (address_reg[2]), .C (n_9), .D
       (address_reg[6]), .Y (n_24));
  INVXL g2433(.A (n_20), .Y (n_106));
  NOR2XL g2386__1666(.A (n_47), .B (n_32), .Y (n_41));
  NOR2BX1 g2387__7410(.AN (n_120), .B (n_98), .Y (n_61));
  INVXL g2420(.A (n_37), .Y (n_19));
  NAND3BXL g2435__6417(.AN (state[2]), .B (state[1]), .C (n_18), .Y
       (n_20));
  NOR3XL g2430__5477(.A (state[1]), .B (n_17), .C (state[0]), .Y
       (n_90));
  INVXL g2459(.A (n_47), .Y (n_28));
  NAND3BXL g2445__2398(.AN (n_17), .B (n_16), .C (state[0]), .Y
       (n_111));
  NOR3X1 g2436__5107(.A (state[1]), .B (state[2]), .C (n_18), .Y
       (n_92));
  NAND3BXL g2444__5526(.AN (state[2]), .B (state[1]), .C (state[0]), .Y
       (n_98));
  NAND2XL g2410__6783(.A (n_12), .B (counter[2]), .Y (n_32));
  NOR3XL g2431__1617(.A (state[2]), .B (state[1]), .C (state[0]), .Y
       (n_25));
  NOR2XL g2423__2802(.A (n_34), .B (n_33), .Y (n_37));
  DFFNSRX1 start_event_reg(.RN (n_138), .SN (1'b1), .CKN (sda), .D
       (scl), .Q (start_event), .QN (n_2));
  NAND2XL g2460__1705(.A (n_34), .B (n_33), .Y (n_47));
  NOR2XL g2447__5122(.A (address_reg[3]), .B (address_reg[7]), .Y
       (n_9));
  INVXL g2366(.A (sda), .Y (n_8));
  NOR2XL g2448__8246(.A (counter[2]), .B (counter[3]), .Y (n_27));
  INVXL g2438(.A (address_reg[6]), .Y (n_7));
  INVXL g2454(.A (address_reg[7]), .Y (n_6));
  INVXL g2455(.A (counter[3]), .Y (n_12));
  INVXL g2453(.A (address_reg[1]), .Y (n_23));
  INVXL g2440(.A (address_reg[4]), .Y (n_55));
  INVXL g2449(.A (state[1]), .Y (n_16));
  INVXL g2446(.A (state[2]), .Y (n_17));
  INVXL g2461(.A (counter[0]), .Y (n_34));
  INVXL g2439(.A (address_reg[5]), .Y (n_5));
  INVXL g2451(.A (address_reg[3]), .Y (n_4));
  INVXL g2452(.A (address_reg[2]), .Y (n_3));
  INVXL g2377(.A (address_reg[0]), .Y (n_115));
  INVXL g2450(.A (state[0]), .Y (n_18));
  INVXL g2458(.A (counter[2]), .Y (n_65));
  INVXL g2462(.A (counter[1]), .Y (n_33));
  TBUFXL g3__7098(.A (1'b0), .OE (n_0), .Y (sda));
  DFFSHQX1 \state_reg[0] (.SN (n_2), .CK (stop_event), .D (1'b0), .Q
       (state[0]));
  NAND2XL g2424__6131(.A (stop_event), .B (n_2), .Y (n_120));
  NOR2BX1 g2392__1881(.AN (sda_drive_en), .B (stop_event), .Y (n_0));
  INVXL g2492(.A (n_154), .Y (n_121));
  AOI21X1 g2(.A0 (n_111), .A1 (n_98), .B0 (n_99), .Y (n_150));
  NOR2XL g2415__2493(.A (counter[1]), .B (n_34), .Y (n_151));
  NOR2XL g2416__2494(.A (counter[0]), .B (n_33), .Y (n_152));
  NOR4X1 g2495(.A (n_70), .B (n_106), .C (n_84), .D (n_71), .Y (n_153));
  NOR2BX1 g2496(.AN (n_61), .B (n_69), .Y (n_154));
  NAND2BX1 g2497(.AN (n_111), .B (start_event), .Y (n_155));
endmodule

