/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module i2c_master_controller(clk, rst, address, data_in, enable, rw, data_out, ready, i2c_sda, i2c_scl);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  input [6:0] address;
  wire [6:0] address;
  wire \address_reg[0] ;
  wire \address_reg[1] ;
  wire \address_reg[2] ;
  wire \address_reg[3] ;
  wire \address_reg[4] ;
  wire \address_reg[5] ;
  wire \address_reg[6] ;
  wire \address_reg[7] ;
  input clk;
  wire clk;
  wire \clk_counter[0] ;
  wire \clk_counter[1] ;
  wire \clk_counter[2] ;
  wire \counter[0] ;
  wire \counter[1] ;
  wire \counter[2] ;
  wire \counter[3] ;
  input [7:0] data_in;
  wire [7:0] data_in;
  output [7:0] data_out;
  wire [7:0] data_out;
  input enable;
  wire enable;
  wire i2c_clk;
  inout i2c_scl;
  wire i2c_scl;
  inout i2c_sda;
  wire i2c_sda;
  output ready;
  wire ready;
  input rst;
  wire rst;
  input rw;
  wire rw;
  wire scl_enable;
  wire sda_drive_en;
  wire sda_out;
  wire \state[0] ;
  wire \state[1] ;
  wire \state[2] ;
  wire \state[3] ;
  wire \state[4] ;
  wire \state[5] ;
  wire \state[6] ;
  wire \state[7] ;
  wire \state[8] ;
  wire \state[9] ;
  wire \write_data_reg[0] ;
  wire \write_data_reg[1] ;
  wire \write_data_reg[2] ;
  wire \write_data_reg[3] ;
  wire \write_data_reg[4] ;
  wire \write_data_reg[5] ;
  wire \write_data_reg[6] ;
  wire \write_data_reg[7] ;
  sky130_fd_sc_hd__inv_2 _135_ (
    .A(rst),
    .Y(_028_)
  );
  sky130_fd_sc_hd__inv_2 _136_ (
    .A(sda_drive_en),
    .Y(_134_)
  );
  sky130_fd_sc_hd__inv_2 _137_ (
    .A(\state[9] ),
    .Y(_064_)
  );
  sky130_fd_sc_hd__inv_2 _138_ (
    .A(i2c_clk),
    .Y(_025_)
  );
  sky130_fd_sc_hd__inv_2 _139_ (
    .A(i2c_sda),
    .Y(_065_)
  );
  sky130_fd_sc_hd__inv_2 _140_ (
    .A(\counter[2] ),
    .Y(_066_)
  );
  sky130_fd_sc_hd__inv_2 _141_ (
    .A(\state[0] ),
    .Y(_067_)
  );
  sky130_fd_sc_hd__inv_2 _142_ (
    .A(\clk_counter[0] ),
    .Y(_000_)
  );
  sky130_fd_sc_hd__inv_2 _143_ (
    .A(\address_reg[0] ),
    .Y(_068_)
  );
  sky130_fd_sc_hd__or2_2 _144_ (
    .A(\counter[0] ),
    .B(\counter[1] ),
    .X(_069_)
  );
  sky130_fd_sc_hd__inv_2 _145_ (
    .A(_069_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__o21ba_2 _146_ (
    .A1(\address_reg[0] ),
    .A2(_069_),
    .B1_N(\state[7] ),
    .X(_071_)
  );
  sky130_fd_sc_hd__and2_2 _147_ (
    .A(\counter[0] ),
    .B(\counter[1] ),
    .X(_072_)
  );
  sky130_fd_sc_hd__nand2_2 _148_ (
    .A(\counter[0] ),
    .B(\counter[1] ),
    .Y(_073_)
  );
  sky130_fd_sc_hd__and2b_2 _149_ (
    .A_N(\counter[0] ),
    .B(\counter[1] ),
    .X(_074_)
  );
  sky130_fd_sc_hd__nand2b_2 _150_ (
    .A_N(\counter[0] ),
    .B(\counter[1] ),
    .Y(_075_)
  );
  sky130_fd_sc_hd__or3b_2 _151_ (
    .A(\counter[0] ),
    .B(\address_reg[2] ),
    .C_N(\counter[1] ),
    .X(_076_)
  );
  sky130_fd_sc_hd__nand2b_2 _152_ (
    .A_N(\counter[1] ),
    .B(\counter[0] ),
    .Y(_077_)
  );
  sky130_fd_sc_hd__inv_2 _153_ (
    .A(_077_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__o221a_2 _154_ (
    .A1(\address_reg[3] ),
    .A2(_073_),
    .B1(_077_),
    .B2(\address_reg[1] ),
    .C1(_076_),
    .X(_079_)
  );
  sky130_fd_sc_hd__o21a_2 _155_ (
    .A1(\write_data_reg[3] ),
    .A2(_073_),
    .B1(\state[7] ),
    .X(_080_)
  );
  sky130_fd_sc_hd__or3_2 _156_ (
    .A(\counter[0] ),
    .B(\counter[1] ),
    .C(\write_data_reg[0] ),
    .X(_081_)
  );
  sky130_fd_sc_hd__o221a_2 _157_ (
    .A1(\write_data_reg[2] ),
    .A2(_075_),
    .B1(_077_),
    .B2(\write_data_reg[1] ),
    .C1(_081_),
    .X(_082_)
  );
  sky130_fd_sc_hd__a22o_2 _158_ (
    .A1(_071_),
    .A2(_079_),
    .B1(_080_),
    .B2(_082_),
    .X(_083_)
  );
  sky130_fd_sc_hd__nor2_2 _159_ (
    .A(\state[8] ),
    .B(\state[7] ),
    .Y(_084_)
  );
  sky130_fd_sc_hd__mux2_1 _160_ (
    .A0(\address_reg[4] ),
    .A1(\write_data_reg[4] ),
    .S(\state[7] ),
    .X(_085_)
  );
  sky130_fd_sc_hd__mux2_1 _161_ (
    .A0(\address_reg[7] ),
    .A1(\write_data_reg[7] ),
    .S(\state[7] ),
    .X(_086_)
  );
  sky130_fd_sc_hd__mux2_1 _162_ (
    .A0(\address_reg[5] ),
    .A1(\write_data_reg[5] ),
    .S(\state[7] ),
    .X(_087_)
  );
  sky130_fd_sc_hd__mux2_1 _163_ (
    .A0(\address_reg[6] ),
    .A1(\write_data_reg[6] ),
    .S(\state[7] ),
    .X(_088_)
  );
  sky130_fd_sc_hd__or2_2 _164_ (
    .A(_075_),
    .B(_088_),
    .X(_089_)
  );
  sky130_fd_sc_hd__o21a_2 _165_ (
    .A1(_073_),
    .A2(_086_),
    .B1(\counter[2] ),
    .X(_090_)
  );
  sky130_fd_sc_hd__o22a_2 _166_ (
    .A1(_069_),
    .A2(_085_),
    .B1(_087_),
    .B2(_077_),
    .X(_091_)
  );
  sky130_fd_sc_hd__a31o_2 _167_ (
    .A1(_089_),
    .A2(_090_),
    .A3(_091_),
    .B1(_084_),
    .X(_092_)
  );
  sky130_fd_sc_hd__a21o_2 _168_ (
    .A1(_066_),
    .A2(_083_),
    .B1(_092_),
    .X(_093_)
  );
  sky130_fd_sc_hd__nor3_2 _169_ (
    .A(\state[1] ),
    .B(\state[3] ),
    .C(\state[5] ),
    .Y(_094_)
  );
  sky130_fd_sc_hd__or3_2 _170_ (
    .A(sda_out),
    .B(\state[8] ),
    .C(\state[7] ),
    .X(_095_)
  );
  sky130_fd_sc_hd__a31o_2 _171_ (
    .A1(_093_),
    .A2(_094_),
    .A3(_095_),
    .B1(\state[6] ),
    .X(_047_)
  );
  sky130_fd_sc_hd__or4_2 _172_ (
    .A(_134_),
    .B(\state[9] ),
    .C(\state[4] ),
    .D(\state[2] ),
    .X(_096_)
  );
  sky130_fd_sc_hd__or4bb_2 _173_ (
    .A(\state[7] ),
    .B(\state[6] ),
    .C_N(_094_),
    .D_N(_096_),
    .X(_046_)
  );
  sky130_fd_sc_hd__or3_2 _174_ (
    .A(_000_),
    .B(\clk_counter[1] ),
    .C(\clk_counter[2] ),
    .X(_097_)
  );
  sky130_fd_sc_hd__xnor2_2 _175_ (
    .A(i2c_clk),
    .B(_097_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nand2_2 _176_ (
    .A(_065_),
    .B(enable),
    .Y(_098_)
  );
  sky130_fd_sc_hd__a221o_2 _177_ (
    .A1(i2c_sda),
    .A2(\state[2] ),
    .B1(_098_),
    .B2(\state[4] ),
    .C1(\state[1] ),
    .X(_009_)
  );
  sky130_fd_sc_hd__nor2_2 _178_ (
    .A(\counter[2] ),
    .B(_069_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nor4_2 _179_ (
    .A(\counter[0] ),
    .B(\counter[1] ),
    .C(\counter[3] ),
    .D(\counter[2] ),
    .Y(_100_)
  );
  sky130_fd_sc_hd__or3_2 _180_ (
    .A(\counter[3] ),
    .B(\counter[2] ),
    .C(_069_),
    .X(_101_)
  );
  sky130_fd_sc_hd__a32o_2 _181_ (
    .A1(_065_),
    .A2(\state[2] ),
    .A3(_068_),
    .B1(_101_),
    .B2(\state[7] ),
    .X(_010_)
  );
  sky130_fd_sc_hd__a21o_2 _182_ (
    .A1(\state[8] ),
    .A2(_101_),
    .B1(\state[3] ),
    .X(_011_)
  );
  sky130_fd_sc_hd__a32o_2 _183_ (
    .A1(_065_),
    .A2(\state[2] ),
    .A3(\address_reg[0] ),
    .B1(_101_),
    .B2(\state[9] ),
    .X(_012_)
  );
  sky130_fd_sc_hd__nor2_2 _184_ (
    .A(enable),
    .B(_067_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__a311o_2 _185_ (
    .A1(_065_),
    .A2(enable),
    .A3(\state[4] ),
    .B1(\state[6] ),
    .C1(_102_),
    .X(_008_)
  );
  sky130_fd_sc_hd__nor2_2 _186_ (
    .A(rst),
    .B(_067_),
    .Y(ready)
  );
  sky130_fd_sc_hd__nand2_2 _187_ (
    .A(_025_),
    .B(scl_enable),
    .Y(i2c_scl)
  );
  sky130_fd_sc_hd__nand2_2 _188_ (
    .A(\clk_counter[0] ),
    .B(\clk_counter[1] ),
    .Y(_103_)
  );
  sky130_fd_sc_hd__or2_2 _189_ (
    .A(\clk_counter[0] ),
    .B(\clk_counter[1] ),
    .X(_104_)
  );
  sky130_fd_sc_hd__o211a_2 _190_ (
    .A1(_000_),
    .A2(\clk_counter[2] ),
    .B1(_103_),
    .C1(_104_),
    .X(_001_)
  );
  sky130_fd_sc_hd__xnor2_2 _191_ (
    .A(\clk_counter[2] ),
    .B(_103_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nor3_2 _192_ (
    .A(\state[0] ),
    .B(\state[6] ),
    .C(\state[5] ),
    .Y(_003_)
  );
  sky130_fd_sc_hd__and2_2 _193_ (
    .A(enable),
    .B(\state[0] ),
    .X(_007_)
  );
  sky130_fd_sc_hd__and2_2 _194_ (
    .A(\state[7] ),
    .B(_100_),
    .X(_006_)
  );
  sky130_fd_sc_hd__nor2_2 _195_ (
    .A(_064_),
    .B(_101_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__and2_2 _196_ (
    .A(\state[8] ),
    .B(_100_),
    .X(_005_)
  );
  sky130_fd_sc_hd__or3_2 _197_ (
    .A(\state[9] ),
    .B(\state[8] ),
    .C(\state[7] ),
    .X(_105_)
  );
  sky130_fd_sc_hd__a221oi_2 _198_ (
    .A1(i2c_sda),
    .A2(\state[2] ),
    .B1(_100_),
    .B2(_105_),
    .C1(rst),
    .Y(_106_)
  );
  sky130_fd_sc_hd__o31a_2 _199_ (
    .A1(\state[2] ),
    .A2(\state[3] ),
    .A3(_105_),
    .B1(_106_),
    .X(_107_)
  );
  sky130_fd_sc_hd__inv_2 _200_ (
    .A(_107_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__nand2_2 _201_ (
    .A(_105_),
    .B(_106_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__mux2_1 _202_ (
    .A0(_107_),
    .A1(_109_),
    .S(\counter[0] ),
    .X(_034_)
  );
  sky130_fd_sc_hd__o32a_2 _203_ (
    .A1(_070_),
    .A2(_072_),
    .A3(_109_),
    .B1(_107_),
    .B2(\counter[1] ),
    .X(_035_)
  );
  sky130_fd_sc_hd__nor2_2 _204_ (
    .A(_066_),
    .B(_070_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__o32a_2 _205_ (
    .A1(_099_),
    .A2(_109_),
    .A3(_110_),
    .B1(_107_),
    .B2(\counter[2] ),
    .X(_036_)
  );
  sky130_fd_sc_hd__o21a_2 _206_ (
    .A1(\counter[2] ),
    .A2(_069_),
    .B1(\counter[3] ),
    .X(_111_)
  );
  sky130_fd_sc_hd__nor2_2 _207_ (
    .A(_100_),
    .B(_111_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _208_ (
    .A1_N(_112_),
    .A2_N(_109_),
    .B1(_108_),
    .B2(\counter[3] ),
    .X(_037_)
  );
  sky130_fd_sc_hd__and3b_2 _209_ (
    .A_N(rst),
    .B(enable),
    .C(\state[0] ),
    .X(_113_)
  );
  sky130_fd_sc_hd__a31oi_2 _210_ (
    .A1(_028_),
    .A2(\state[9] ),
    .A3(_067_),
    .B1(_113_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__nor2_2 _211_ (
    .A(_101_),
    .B(_114_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _212_ (
    .A1_N(data_out[0]),
    .A2_N(_115_),
    .B1(_113_),
    .B2(_064_),
    .X(_116_)
  );
  sky130_fd_sc_hd__a21oi_2 _213_ (
    .A1(_065_),
    .A2(_115_),
    .B1(_116_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nor3_2 _214_ (
    .A(\counter[3] ),
    .B(\counter[2] ),
    .C(_077_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__o21bai_2 _215_ (
    .A1(_064_),
    .A2(_117_),
    .B1_N(_114_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__nor2_2 _216_ (
    .A(_064_),
    .B(_114_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__a32o_2 _217_ (
    .A1(i2c_sda),
    .A2(_117_),
    .A3(_119_),
    .B1(_118_),
    .B2(data_out[1]),
    .X(_039_)
  );
  sky130_fd_sc_hd__and3_2 _218_ (
    .A(i2c_sda),
    .B(_112_),
    .C(_119_),
    .X(_120_)
  );
  sky130_fd_sc_hd__or3_2 _219_ (
    .A(\counter[3] ),
    .B(\counter[2] ),
    .C(_075_),
    .X(_121_)
  );
  sky130_fd_sc_hd__a21o_2 _220_ (
    .A1(\state[9] ),
    .A2(_121_),
    .B1(_114_),
    .X(_122_)
  );
  sky130_fd_sc_hd__a32o_2 _221_ (
    .A1(_066_),
    .A2(_074_),
    .A3(_120_),
    .B1(_122_),
    .B2(data_out[2]),
    .X(_040_)
  );
  sky130_fd_sc_hd__o31a_2 _222_ (
    .A1(\counter[3] ),
    .A2(\counter[2] ),
    .A3(_073_),
    .B1(\state[9] ),
    .X(_123_)
  );
  sky130_fd_sc_hd__o21a_2 _223_ (
    .A1(_114_),
    .A2(_123_),
    .B1(data_out[3]),
    .X(_124_)
  );
  sky130_fd_sc_hd__a31o_2 _224_ (
    .A1(_066_),
    .A2(_072_),
    .A3(_120_),
    .B1(_124_),
    .X(_041_)
  );
  sky130_fd_sc_hd__or2_2 _225_ (
    .A(\counter[3] ),
    .B(_066_),
    .X(_125_)
  );
  sky130_fd_sc_hd__or2_2 _226_ (
    .A(_069_),
    .B(_125_),
    .X(_126_)
  );
  sky130_fd_sc_hd__mux2_1 _227_ (
    .A0(i2c_sda),
    .A1(data_out[4]),
    .S(_126_),
    .X(_127_)
  );
  sky130_fd_sc_hd__a22o_2 _228_ (
    .A1(data_out[4]),
    .A2(_114_),
    .B1(_119_),
    .B2(_127_),
    .X(_042_)
  );
  sky130_fd_sc_hd__o21a_2 _229_ (
    .A1(_077_),
    .A2(_125_),
    .B1(data_out[5]),
    .X(_128_)
  );
  sky130_fd_sc_hd__a22o_2 _230_ (
    .A1(data_out[5]),
    .A2(_114_),
    .B1(_119_),
    .B2(_128_),
    .X(_129_)
  );
  sky130_fd_sc_hd__a31o_2 _231_ (
    .A1(\counter[2] ),
    .A2(_078_),
    .A3(_120_),
    .B1(_129_),
    .X(_043_)
  );
  sky130_fd_sc_hd__o21a_2 _232_ (
    .A1(_075_),
    .A2(_125_),
    .B1(data_out[6]),
    .X(_130_)
  );
  sky130_fd_sc_hd__a22o_2 _233_ (
    .A1(data_out[6]),
    .A2(_114_),
    .B1(_119_),
    .B2(_130_),
    .X(_131_)
  );
  sky130_fd_sc_hd__a31o_2 _234_ (
    .A1(\counter[2] ),
    .A2(_074_),
    .A3(_120_),
    .B1(_131_),
    .X(_044_)
  );
  sky130_fd_sc_hd__o21bai_2 _235_ (
    .A1(_073_),
    .A2(_125_),
    .B1_N(data_out[7]),
    .Y(_132_)
  );
  sky130_fd_sc_hd__or3_2 _236_ (
    .A(i2c_sda),
    .B(_073_),
    .C(_125_),
    .X(_133_)
  );
  sky130_fd_sc_hd__a32o_2 _237_ (
    .A1(_119_),
    .A2(_132_),
    .A3(_133_),
    .B1(_114_),
    .B2(data_out[7]),
    .X(_045_)
  );
  sky130_fd_sc_hd__mux2_1 _238_ (
    .A0(\address_reg[0] ),
    .A1(rw),
    .S(_113_),
    .X(_048_)
  );
  sky130_fd_sc_hd__mux2_1 _239_ (
    .A0(\address_reg[1] ),
    .A1(address[0]),
    .S(_113_),
    .X(_049_)
  );
  sky130_fd_sc_hd__mux2_1 _240_ (
    .A0(\address_reg[2] ),
    .A1(address[1]),
    .S(_113_),
    .X(_050_)
  );
  sky130_fd_sc_hd__mux2_1 _241_ (
    .A0(\address_reg[3] ),
    .A1(address[2]),
    .S(_113_),
    .X(_051_)
  );
  sky130_fd_sc_hd__mux2_1 _242_ (
    .A0(\address_reg[4] ),
    .A1(address[3]),
    .S(_113_),
    .X(_052_)
  );
  sky130_fd_sc_hd__mux2_1 _243_ (
    .A0(\address_reg[5] ),
    .A1(address[4]),
    .S(_113_),
    .X(_053_)
  );
  sky130_fd_sc_hd__mux2_1 _244_ (
    .A0(\address_reg[6] ),
    .A1(address[5]),
    .S(_113_),
    .X(_054_)
  );
  sky130_fd_sc_hd__mux2_1 _245_ (
    .A0(\address_reg[7] ),
    .A1(address[6]),
    .S(_113_),
    .X(_055_)
  );
  sky130_fd_sc_hd__mux2_1 _246_ (
    .A0(\write_data_reg[0] ),
    .A1(data_in[0]),
    .S(_113_),
    .X(_056_)
  );
  sky130_fd_sc_hd__mux2_1 _247_ (
    .A0(\write_data_reg[1] ),
    .A1(data_in[1]),
    .S(_113_),
    .X(_057_)
  );
  sky130_fd_sc_hd__mux2_1 _248_ (
    .A0(\write_data_reg[2] ),
    .A1(data_in[2]),
    .S(_113_),
    .X(_058_)
  );
  sky130_fd_sc_hd__mux2_1 _249_ (
    .A0(\write_data_reg[3] ),
    .A1(data_in[3]),
    .S(_113_),
    .X(_059_)
  );
  sky130_fd_sc_hd__mux2_1 _250_ (
    .A0(\write_data_reg[4] ),
    .A1(data_in[4]),
    .S(_113_),
    .X(_060_)
  );
  sky130_fd_sc_hd__mux2_1 _251_ (
    .A0(\write_data_reg[5] ),
    .A1(data_in[5]),
    .S(_113_),
    .X(_061_)
  );
  sky130_fd_sc_hd__mux2_1 _252_ (
    .A0(\write_data_reg[6] ),
    .A1(data_in[6]),
    .S(_113_),
    .X(_062_)
  );
  sky130_fd_sc_hd__mux2_1 _253_ (
    .A0(\write_data_reg[7] ),
    .A1(data_in[7]),
    .S(_113_),
    .X(_063_)
  );
  sky130_fd_sc_hd__inv_2 _254_ (
    .A(rst),
    .Y(_026_)
  );
  sky130_fd_sc_hd__inv_2 _255_ (
    .A(rst),
    .Y(_024_)
  );
  sky130_fd_sc_hd__inv_2 _256_ (
    .A(rst),
    .Y(_013_)
  );
  sky130_fd_sc_hd__inv_2 _257_ (
    .A(rst),
    .Y(_014_)
  );
  sky130_fd_sc_hd__inv_2 _258_ (
    .A(rst),
    .Y(_015_)
  );
  sky130_fd_sc_hd__inv_2 _259_ (
    .A(rst),
    .Y(_016_)
  );
  sky130_fd_sc_hd__inv_2 _260_ (
    .A(rst),
    .Y(_017_)
  );
  sky130_fd_sc_hd__inv_2 _261_ (
    .A(rst),
    .Y(_018_)
  );
  sky130_fd_sc_hd__inv_2 _262_ (
    .A(rst),
    .Y(_019_)
  );
  sky130_fd_sc_hd__inv_2 _263_ (
    .A(rst),
    .Y(_020_)
  );
  sky130_fd_sc_hd__inv_2 _264_ (
    .A(rst),
    .Y(_021_)
  );
  sky130_fd_sc_hd__inv_2 _265_ (
    .A(rst),
    .Y(_022_)
  );
  sky130_fd_sc_hd__inv_2 _266_ (
    .A(rst),
    .Y(_023_)
  );
  sky130_fd_sc_hd__inv_2 _267_ (
    .A(i2c_clk),
    .Y(_027_)
  );
  sky130_fd_sc_hd__inv_2 _268_ (
    .A(i2c_clk),
    .Y(_029_)
  );
  sky130_fd_sc_hd__inv_2 _269_ (
    .A(rst),
    .Y(_030_)
  );
  sky130_fd_sc_hd__inv_2 _270_ (
    .A(rst),
    .Y(_031_)
  );
  sky130_fd_sc_hd__inv_2 _271_ (
    .A(rst),
    .Y(_032_)
  );
  sky130_fd_sc_hd__dfstp_2 _272_ (
    .CLK(clk),
    .D(_033_),
    .Q(i2c_clk),
    .SET_B(_013_)
  );
  sky130_fd_sc_hd__dfxtp_2 _273_ (
    .CLK(i2c_clk),
    .D(_034_),
    .Q(\counter[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _274_ (
    .CLK(i2c_clk),
    .D(_035_),
    .Q(\counter[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _275_ (
    .CLK(i2c_clk),
    .D(_036_),
    .Q(\counter[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _276_ (
    .CLK(i2c_clk),
    .D(_037_),
    .Q(\counter[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _277_ (
    .CLK(i2c_clk),
    .D(_038_),
    .Q(data_out[0])
  );
  sky130_fd_sc_hd__dfxtp_2 _278_ (
    .CLK(i2c_clk),
    .D(_039_),
    .Q(data_out[1])
  );
  sky130_fd_sc_hd__dfxtp_2 _279_ (
    .CLK(i2c_clk),
    .D(_040_),
    .Q(data_out[2])
  );
  sky130_fd_sc_hd__dfxtp_2 _280_ (
    .CLK(i2c_clk),
    .D(_041_),
    .Q(data_out[3])
  );
  sky130_fd_sc_hd__dfxtp_2 _281_ (
    .CLK(i2c_clk),
    .D(_042_),
    .Q(data_out[4])
  );
  sky130_fd_sc_hd__dfxtp_2 _282_ (
    .CLK(i2c_clk),
    .D(_043_),
    .Q(data_out[5])
  );
  sky130_fd_sc_hd__dfxtp_2 _283_ (
    .CLK(i2c_clk),
    .D(_044_),
    .Q(data_out[6])
  );
  sky130_fd_sc_hd__dfxtp_2 _284_ (
    .CLK(i2c_clk),
    .D(_045_),
    .Q(data_out[7])
  );
  sky130_fd_sc_hd__dfstp_2 _285_ (
    .CLK(i2c_clk),
    .D(_008_),
    .Q(\state[0] ),
    .SET_B(_014_)
  );
  sky130_fd_sc_hd__dfrtp_2 _286_ (
    .CLK(i2c_clk),
    .D(_004_),
    .Q(\state[1] ),
    .RESET_B(_015_)
  );
  sky130_fd_sc_hd__dfrtp_2 _287_ (
    .CLK(i2c_clk),
    .D(_005_),
    .Q(\state[2] ),
    .RESET_B(_016_)
  );
  sky130_fd_sc_hd__dfrtp_2 _288_ (
    .CLK(i2c_clk),
    .D(\state[5] ),
    .Q(\state[3] ),
    .RESET_B(_017_)
  );
  sky130_fd_sc_hd__dfrtp_2 _289_ (
    .CLK(i2c_clk),
    .D(_006_),
    .Q(\state[4] ),
    .RESET_B(_018_)
  );
  sky130_fd_sc_hd__dfrtp_2 _290_ (
    .CLK(i2c_clk),
    .D(_007_),
    .Q(\state[5] ),
    .RESET_B(_019_)
  );
  sky130_fd_sc_hd__dfrtp_2 _291_ (
    .CLK(i2c_clk),
    .D(_009_),
    .Q(\state[6] ),
    .RESET_B(_020_)
  );
  sky130_fd_sc_hd__dfrtp_2 _292_ (
    .CLK(i2c_clk),
    .D(_010_),
    .Q(\state[7] ),
    .RESET_B(_021_)
  );
  sky130_fd_sc_hd__dfrtp_2 _293_ (
    .CLK(i2c_clk),
    .D(_011_),
    .Q(\state[8] ),
    .RESET_B(_022_)
  );
  sky130_fd_sc_hd__dfrtp_2 _294_ (
    .CLK(i2c_clk),
    .D(_012_),
    .Q(\state[9] ),
    .RESET_B(_023_)
  );
  sky130_fd_sc_hd__dfstp_2 _295_ (
    .CLK(_025_),
    .D(_046_),
    .Q(sda_drive_en),
    .SET_B(_024_)
  );
  sky130_fd_sc_hd__dfstp_2 _296_ (
    .CLK(_027_),
    .D(_047_),
    .Q(sda_out),
    .SET_B(_026_)
  );
  sky130_fd_sc_hd__dfxtp_2 _297_ (
    .CLK(i2c_clk),
    .D(_048_),
    .Q(\address_reg[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _298_ (
    .CLK(i2c_clk),
    .D(_049_),
    .Q(\address_reg[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _299_ (
    .CLK(i2c_clk),
    .D(_050_),
    .Q(\address_reg[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _300_ (
    .CLK(i2c_clk),
    .D(_051_),
    .Q(\address_reg[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _301_ (
    .CLK(i2c_clk),
    .D(_052_),
    .Q(\address_reg[4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _302_ (
    .CLK(i2c_clk),
    .D(_053_),
    .Q(\address_reg[5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _303_ (
    .CLK(i2c_clk),
    .D(_054_),
    .Q(\address_reg[6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _304_ (
    .CLK(i2c_clk),
    .D(_055_),
    .Q(\address_reg[7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _305_ (
    .CLK(i2c_clk),
    .D(_056_),
    .Q(\write_data_reg[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _306_ (
    .CLK(i2c_clk),
    .D(_057_),
    .Q(\write_data_reg[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _307_ (
    .CLK(i2c_clk),
    .D(_058_),
    .Q(\write_data_reg[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _308_ (
    .CLK(i2c_clk),
    .D(_059_),
    .Q(\write_data_reg[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _309_ (
    .CLK(i2c_clk),
    .D(_060_),
    .Q(\write_data_reg[4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _310_ (
    .CLK(i2c_clk),
    .D(_061_),
    .Q(\write_data_reg[5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _311_ (
    .CLK(i2c_clk),
    .D(_062_),
    .Q(\write_data_reg[6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _312_ (
    .CLK(i2c_clk),
    .D(_063_),
    .Q(\write_data_reg[7] )
  );
  sky130_fd_sc_hd__dfrtp_2 _313_ (
    .CLK(_029_),
    .D(_003_),
    .Q(scl_enable),
    .RESET_B(_028_)
  );
  sky130_fd_sc_hd__dfrtp_2 _314_ (
    .CLK(clk),
    .D(_000_),
    .Q(\clk_counter[0] ),
    .RESET_B(_030_)
  );
  sky130_fd_sc_hd__dfrtp_2 _315_ (
    .CLK(clk),
    .D(_001_),
    .Q(\clk_counter[1] ),
    .RESET_B(_031_)
  );
  sky130_fd_sc_hd__dfrtp_2 _316_ (
    .CLK(clk),
    .D(_002_),
    .Q(\clk_counter[2] ),
    .RESET_B(_032_)
  );
  sky130_fd_sc_hd__ebufn_2 _317_ (
    .A(sda_out),
    .TE_B(_134_),
    .Z(i2c_sda)
  );
endmodule
