/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

(* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:1.1-217.10" *)
module i2c_master_controller(clk, rst, address, data_in, enable, rw, data_out, ready, i2c_sda, i2c_scl);
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:59.5-69.8" *)
  wire [2:0] _000_;
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:74.5-83.8" *)
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:65.28-65.36" *)
  wire _129_;
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:0.0-0.0" *)
  wire _130_;
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:0.0-0.0" *)
  wire _131_;
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:0.0-0.0" *)
  wire _132_;
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:0.0-0.0" *)
  wire _133_;
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:0.0-0.0" *)
  wire _134_;
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:0.0-0.0" *)
  wire _135_;
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:0.0-0.0" *)
  wire _136_;
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:0.0-0.0" *)
  wire _137_;
  (* force_downto = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:0.0-0.0|/nix/store/9r0bh7sp051dpm8km8bqlb028anpd3v3-yosys/bin/../share/yosys/techmap.v:279.21-279.23" *)
  (* unused_bits = "1 2 3" *)
  wire [4:0] _138_;
  (* force_downto = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:116.36-116.47|/nix/store/9r0bh7sp051dpm8km8bqlb028anpd3v3-yosys/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _139_;
  (* force_downto = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:209.17-212.20|/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:172.13-213.20|/nix/store/9r0bh7sp051dpm8km8bqlb028anpd3v3-yosys/bin/../share/yosys/techmap.v:576.21-576.22" *)
  wire _140_;
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:8.35-8.42" *)
  input [6:0] address;
  wire [6:0] address;
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:40.26-40.37" *)
  reg [7:0] address_reg;
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:6.18-6.21" *)
  input clk;
  wire clk;
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:43.37-43.48" *)
  reg [2:0] clk_counter;
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:42.38-42.45" *)
  reg [3:0] counter;
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:9.35-9.42" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:13.35-13.43" *)
  output [7:0] data_out;
  reg [7:0] data_out;
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:10.18-10.24" *)
  input enable;
  wire enable;
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:47.11-47.18" *)
  reg i2c_clk;
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:17.18-17.25" *)
  inout i2c_scl;
  reg i2c_scl;
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:16.18-16.25" *)
  inout i2c_sda;
  reg i2c_sda;
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:14.18-14.23" *)
  output ready;
  wire ready;
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:7.18-7.21" *)
  input rst;
  wire rst;
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:11.18-11.20" *)
  input rw;
  wire rw;
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:46.11-46.21" *)
  reg scl_enable;
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:45.11-45.18" *)
  wire sda_out;
  (* onehot = 32'd1 *)
  reg [9:0] state;
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:41.28-41.42" *)
  reg [7:0] write_data_reg;
  assign _138_[0] = ~counter[0];
  assign _117_ = state[8] | state[7];
  assign _015_ = _117_ | state[9];
  assign _118_ = clk_counter[0] & ~(clk_counter[1]);
  assign _119_ = _118_ & ~(clk_counter[2]);
  assign _120_ = i2c_sda | ~(enable);
  assign _121_ = _120_ & state[4];
  assign _122_ = state[2] & i2c_sda;
  assign _123_ = _122_ | _121_;
  assign _007_ = _123_ | state[1];
  assign _124_ = i2c_sda | address_reg[0];
  assign _125_ = state[2] & ~(_124_);
  assign _116_ = ~(counter[1] | counter[0]);
  assign _126_ = counter[3] | counter[2];
  assign _127_ = _116_ & ~(_126_);
  assign _128_ = state[7] & ~(_127_);
  assign _008_ = _128_ | _125_;
  assign _016_ = rst | ~(enable);
  assign _013_ = state[0] & ~(_016_);
  assign _017_ = ~(_122_ | rst);
  assign _018_ = ~(_015_ | state[2]);
  assign _019_ = _018_ & ~(state[3]);
  assign _020_ = _126_ | ~(_116_);
  assign _021_ = _015_ & ~(_020_);
  assign _022_ = _021_ | _019_;
  assign _012_ = _017_ & ~(_022_);
  assign _023_ = state[8] & ~(_127_);
  assign _009_ = _023_ | state[3];
  assign _024_ = state[9] & ~(_127_);
  assign _025_ = i2c_sda | ~(address_reg[0]);
  assign _026_ = state[2] & ~(_025_);
  assign _010_ = _026_ | _024_;
  assign _027_ = state[4] & ~(_120_);
  assign _028_ = state[0] & ~(enable);
  assign _029_ = _028_ | _027_;
  assign _006_ = _029_ | state[6];
  assign _030_ = state[3] | state[1];
  assign _031_ = _030_ | state[5];
  assign _032_ = _031_ | state[6];
  assign _011_ = _032_ | _117_;
  assign _033_ = ~(state[9] | state[0]);
  assign _034_ = ~(_033_ | rst);
  assign _014_ = _034_ & ~(_028_);
  assign ready = state[0] & ~(rst);
  assign _035_ = state[7] ? write_data_reg[0] : address_reg[0];
  assign _036_ = state[7] ? write_data_reg[1] : address_reg[1];
  assign _037_ = counter[0] ? _036_ : _035_;
  assign _038_ = state[7] ? write_data_reg[2] : address_reg[2];
  assign _039_ = state[7] ? write_data_reg[3] : address_reg[3];
  assign _040_ = counter[0] ? _039_ : _038_;
  assign _041_ = counter[1] ? _040_ : _037_;
  assign _042_ = state[7] ? write_data_reg[4] : address_reg[4];
  assign _043_ = state[7] ? write_data_reg[5] : address_reg[5];
  assign _044_ = counter[0] ? _043_ : _042_;
  assign _045_ = state[7] ? write_data_reg[6] : address_reg[6];
  assign _046_ = state[7] ? write_data_reg[7] : address_reg[7];
  assign _047_ = counter[0] ? _046_ : _045_;
  assign _048_ = counter[1] ? _047_ : _044_;
  assign _049_ = counter[2] ? _048_ : _041_;
  assign _140_ = _032_ ? state[6] : _049_;
  assign i2c_scl = i2c_clk | ~(scl_enable);
  assign _000_[0] = ~(_119_ | clk_counter[0]);
  assign _050_ = clk_counter[1] & ~(clk_counter[0]);
  assign _000_[1] = _118_ ? clk_counter[2] : _050_;
  assign _051_ = clk_counter[0] & clk_counter[1];
  assign _052_ = _051_ ^ clk_counter[2];
  assign _000_[2] = _052_ & ~(_119_);
  assign _129_ = ~i2c_clk;
  assign _053_ = ~(state[5] | state[0]);
  assign _001_ = _053_ & ~(state[6]);
  assign _054_ = _138_[0] & ~(_020_);
  assign _139_[1] = ~(counter[1] ^ counter[0]);
  assign _055_ = ~_139_[1];
  assign _056_ = _054_ & ~(_055_);
  assign _139_[2] = _116_ ^ counter[2];
  assign _057_ = ~_139_[2];
  assign _058_ = _056_ & ~(_057_);
  assign _059_ = _116_ & ~(counter[2]);
  assign _060_ = ~(_059_ ^ counter[3]);
  assign _061_ = _058_ & ~(_060_);
  assign _062_ = data_out[0] & ~(_061_);
  assign _063_ = ~i2c_sda;
  assign _064_ = _020_ | _063_;
  assign _065_ = _064_ | counter[0];
  assign _066_ = _065_ | _055_;
  assign _067_ = _139_[2] & ~(_066_);
  assign _068_ = _067_ & ~(_060_);
  assign _130_ = _068_ | _062_;
  assign _069_ = counter[1] | ~(counter[0]);
  assign _070_ = _069_ | _139_[2];
  assign _071_ = _060_ & ~(_070_);
  assign _072_ = data_out[1] & ~(_071_);
  assign _073_ = ~(i2c_sda & counter[0]);
  assign _074_ = _073_ | _139_[1];
  assign _075_ = _074_ | _139_[2];
  assign _076_ = _060_ & ~(_075_);
  assign _131_ = _076_ | _072_;
  assign _077_ = counter[0] | ~(counter[1]);
  assign _078_ = _077_ | _139_[2];
  assign _079_ = _060_ & ~(_078_);
  assign _080_ = data_out[2] & ~(_079_);
  assign _081_ = _127_ | _063_;
  assign _082_ = _081_ | counter[0];
  assign _083_ = _082_ | _139_[1];
  assign _084_ = _083_ | _139_[2];
  assign _085_ = _060_ & ~(_084_);
  assign _132_ = _085_ | _080_;
  assign _086_ = ~(counter[1] & counter[0]);
  assign _087_ = _086_ | _139_[2];
  assign _088_ = _060_ & ~(_087_);
  assign _089_ = data_out[3] & ~(_088_);
  assign _090_ = _073_ | ~(_139_[1]);
  assign _091_ = _090_ | _139_[2];
  assign _092_ = _060_ & ~(_091_);
  assign _133_ = _092_ | _089_;
  assign _093_ = _127_ | counter[0];
  assign _094_ = _093_ | _055_;
  assign _095_ = _094_ | _139_[2];
  assign _096_ = _060_ & ~(_095_);
  assign _097_ = data_out[4] & ~(_096_);
  assign _098_ = _082_ | _055_;
  assign _099_ = _098_ | _139_[2];
  assign _100_ = _060_ & ~(_099_);
  assign _134_ = _100_ | _097_;
  assign _101_ = _069_ | ~(_139_[2]);
  assign _102_ = _060_ & ~(_101_);
  assign _103_ = data_out[5] & ~(_102_);
  assign _104_ = _074_ | ~(_139_[2]);
  assign _105_ = _060_ & ~(_104_);
  assign _135_ = _105_ | _103_;
  assign _106_ = _077_ | ~(_139_[2]);
  assign _107_ = _060_ & ~(_106_);
  assign _108_ = data_out[6] & ~(_107_);
  assign _109_ = _083_ | _057_;
  assign _110_ = _060_ & ~(_109_);
  assign _136_ = _110_ | _108_;
  assign _111_ = _086_ | ~(_139_[2]);
  assign _112_ = _060_ & ~(_111_);
  assign _113_ = data_out[7] & ~(_112_);
  assign _114_ = _090_ | ~(_139_[2]);
  assign _115_ = _060_ & ~(_114_);
  assign _137_ = _115_ | _113_;
  assign _005_ = enable & state[0];
  assign _004_ = state[7] & ~(_020_);
  assign _002_ = state[9] & ~(_020_);
  assign _003_ = state[8] & ~(_020_);
  assign _139_[3] = _059_ ^ counter[3];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:88.5-162.8" *)
  always @(posedge i2c_clk)
    if (_012_)
      if (!_015_) counter[0] <= 1'h1;
      else counter[0] <= _138_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:88.5-162.8" *)
  always @(posedge i2c_clk)
    if (_012_)
      if (!_015_) counter[1] <= 1'h1;
      else counter[1] <= _139_[1];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:88.5-162.8" *)
  always @(posedge i2c_clk)
    if (_012_)
      if (!_015_) counter[2] <= 1'h1;
      else counter[2] <= _139_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:88.5-162.8" *)
  always @(posedge i2c_clk)
    if (_012_)
      if (!_015_) counter[3] <= 1'h0;
      else counter[3] <= _139_[3];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:59.5-69.8" *)
  always @(posedge clk, posedge rst)
    if (rst) i2c_clk <= 1'h1;
    else if (_119_) i2c_clk <= _129_;
  (* \always_ff  = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:88.5-162.8" *)
  always @(posedge i2c_clk)
    if (_014_)
      if (!state[9]) data_out[0] <= 1'h0;
      else data_out[0] <= _130_;
  (* \always_ff  = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:88.5-162.8" *)
  always @(posedge i2c_clk)
    if (_014_)
      if (!state[9]) data_out[1] <= 1'h0;
      else data_out[1] <= _131_;
  (* \always_ff  = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:88.5-162.8" *)
  always @(posedge i2c_clk)
    if (_014_)
      if (!state[9]) data_out[2] <= 1'h0;
      else data_out[2] <= _132_;
  (* \always_ff  = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:88.5-162.8" *)
  always @(posedge i2c_clk)
    if (_014_)
      if (!state[9]) data_out[3] <= 1'h0;
      else data_out[3] <= _133_;
  (* \always_ff  = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:88.5-162.8" *)
  always @(posedge i2c_clk)
    if (_014_)
      if (!state[9]) data_out[4] <= 1'h0;
      else data_out[4] <= _134_;
  (* \always_ff  = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:88.5-162.8" *)
  always @(posedge i2c_clk)
    if (_014_)
      if (!state[9]) data_out[5] <= 1'h0;
      else data_out[5] <= _135_;
  (* \always_ff  = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:88.5-162.8" *)
  always @(posedge i2c_clk)
    if (_014_)
      if (!state[9]) data_out[6] <= 1'h0;
      else data_out[6] <= _136_;
  (* \always_ff  = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:88.5-162.8" *)
  always @(posedge i2c_clk)
    if (_014_)
      if (!state[9]) data_out[7] <= 1'h0;
      else data_out[7] <= _137_;
  always @(posedge i2c_clk, posedge rst)
    if (rst) state[0] <= 1'h1;
    else state[0] <= _006_;
  always @(posedge i2c_clk, posedge rst)
    if (rst) state[1] <= 1'h0;
    else state[1] <= _002_;
  always @(posedge i2c_clk, posedge rst)
    if (rst) state[2] <= 1'h0;
    else state[2] <= _003_;
  always @(posedge i2c_clk, posedge rst)
    if (rst) state[3] <= 1'h0;
    else state[3] <= state[5];
  always @(posedge i2c_clk, posedge rst)
    if (rst) state[4] <= 1'h0;
    else state[4] <= _004_;
  always @(posedge i2c_clk, posedge rst)
    if (rst) state[5] <= 1'h0;
    else state[5] <= _005_;
  always @(posedge i2c_clk, posedge rst)
    if (rst) state[6] <= 1'h0;
    else state[6] <= _007_;
  always @(posedge i2c_clk, posedge rst)
    if (rst) state[7] <= 1'h0;
    else state[7] <= _008_;
  always @(posedge i2c_clk, posedge rst)
    if (rst) state[8] <= 1'h0;
    else state[8] <= _009_;
  always @(posedge i2c_clk, posedge rst)
    if (rst) state[9] <= 1'h0;
    else state[9] <= _010_;
  (* \always_ff  = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:167.5-215.8" *)
  always @(negedge i2c_clk, posedge rst)
    if (rst) i2c_sda <= 1'h1;
    else if (_011_) i2c_sda <= _140_;
  (* \always_ff  = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:88.5-162.8" *)
  always @(posedge i2c_clk)
    if (_013_) address_reg[0] <= rw;
  (* \always_ff  = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:88.5-162.8" *)
  always @(posedge i2c_clk)
    if (_013_) address_reg[1] <= address[0];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:88.5-162.8" *)
  always @(posedge i2c_clk)
    if (_013_) address_reg[2] <= address[1];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:88.5-162.8" *)
  always @(posedge i2c_clk)
    if (_013_) address_reg[3] <= address[2];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:88.5-162.8" *)
  always @(posedge i2c_clk)
    if (_013_) address_reg[4] <= address[3];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:88.5-162.8" *)
  always @(posedge i2c_clk)
    if (_013_) address_reg[5] <= address[4];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:88.5-162.8" *)
  always @(posedge i2c_clk)
    if (_013_) address_reg[6] <= address[5];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:88.5-162.8" *)
  always @(posedge i2c_clk)
    if (_013_) address_reg[7] <= address[6];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:88.5-162.8" *)
  always @(posedge i2c_clk)
    if (_013_) write_data_reg[0] <= data_in[0];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:88.5-162.8" *)
  always @(posedge i2c_clk)
    if (_013_) write_data_reg[1] <= data_in[1];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:88.5-162.8" *)
  always @(posedge i2c_clk)
    if (_013_) write_data_reg[2] <= data_in[2];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:88.5-162.8" *)
  always @(posedge i2c_clk)
    if (_013_) write_data_reg[3] <= data_in[3];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:88.5-162.8" *)
  always @(posedge i2c_clk)
    if (_013_) write_data_reg[4] <= data_in[4];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:88.5-162.8" *)
  always @(posedge i2c_clk)
    if (_013_) write_data_reg[5] <= data_in[5];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:88.5-162.8" *)
  always @(posedge i2c_clk)
    if (_013_) write_data_reg[6] <= data_in[6];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:88.5-162.8" *)
  always @(posedge i2c_clk)
    if (_013_) write_data_reg[7] <= data_in[7];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:74.5-83.8" *)
  always @(negedge i2c_clk, posedge rst)
    if (rst) scl_enable <= 1'h0;
    else scl_enable <= _001_;
  (* \always_ff  = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:59.5-69.8" *)
  always @(posedge clk, posedge rst)
    if (rst) clk_counter[0] <= 1'h0;
    else clk_counter[0] <= _000_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:59.5-69.8" *)
  always @(posedge clk, posedge rst)
    if (rst) clk_counter[1] <= 1'h0;
    else clk_counter[1] <= _000_[1];
  (* \always_ff  = 32'd1 *)
  (* src = "/home/davidsales/Documentos/Coding/Main_HDL/Synthesis/designs/i2c_master/i2c_master.sv:59.5-69.8" *)
  always @(posedge clk, posedge rst)
    if (rst) clk_counter[2] <= 1'h0;
    else clk_counter[2] <= _000_[2];
  assign _138_[4] = 1'h1;
  assign _139_[0] = _138_[0];
  assign sda_out = i2c_sda;
endmodule
