// Auto-generated by LibreLane
module i2c_master_controller(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst,
  input[6:0] address,
  input[7:0] data_in,
  input enable,
  input rw,
  output[7:0] data_out,
  output ready,
  inout i2c_sda,
  inout i2c_scl
);
endmodule
