
// Generated by Cadence Genus(TM) Synthesis Solution 22.16-s078_1
// Generated on: Mar 18 2026 18:09:35 -03 (Mar 18 2026 21:09:35 UTC)

// Verification Directory fv/i2c_slave_controller 

module i2c_slave_controller(sda, scl, rst, data_received, data_to_send);
  input scl, rst;
  input [7:0] data_to_send;
  output [7:0] data_received;
  inout sda;
  wire scl, rst;
  wire [7:0] data_to_send;
  wire [7:0] data_received;
  wire sda;
  wire [3:0] counter;
  wire [2:0] state;
  wire [7:0] address_reg;
  wire UNCONNECTED, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_22, n_23, n_24;
  wire n_26, n_27, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52, n_53, n_54, n_55, n_56, n_57, n_58;
  wire n_59, n_60, n_61, n_62, n_63, n_64, n_65, n_66;
  wire n_67, n_68, n_69, n_70, n_71, n_72, n_73, n_74;
  wire n_75, n_77, n_78, n_79, n_80, n_81, n_82, n_83;
  wire n_84, n_85, n_86, n_87, n_88, n_89, n_90, n_91;
  wire n_92, n_93, n_94, n_95, n_96, n_97, n_98, n_99;
  wire n_100, n_101, n_102, n_103, n_104, n_105, n_106, n_107;
  wire n_119, n_120, n_121, sda_drive_en, start_event;
  DFFRHQX1 \counter_reg[2] (.RN (n_107), .CK (scl), .D (n_101), .Q
       (counter[2]));
  DFFNSRX1 sda_drive_en_reg(.RN (n_107), .SN (1'b1), .CKN (scl), .D
       (n_100), .Q (sda_drive_en), .QN (UNCONNECTED));
  OAI211X1 g1597__2398(.A0 (n_9), .A1 (n_104), .B0 (n_18), .C0 (n_103),
       .Y (n_106));
  DFFRHQX1 \state_reg[2] (.RN (n_107), .CK (scl), .D (n_98), .Q
       (state[2]));
  OAI211X1 g1611__5107(.A0 (n_104), .A1 (n_69), .B0 (n_119), .C0
       (n_103), .Y (n_105));
  OAI211X1 g1595__6260(.A0 (n_15), .A1 (n_80), .B0 (n_59), .C0 (n_95),
       .Y (n_102));
  NAND3XL g1596__4319(.A (n_6), .B (n_120), .C (n_103), .Y (n_101));
  NAND4XL g1598__8428(.A (n_27), .B (n_94), .C (n_84), .D (n_86), .Y
       (n_100));
  OAI211X1 g1612__5526(.A0 (n_45), .A1 (n_97), .B0 (n_57), .C0 (n_89),
       .Y (n_99));
  DFFRHQX1 \address_reg_reg[0] (.RN (n_107), .CK (scl), .D (n_96), .Q
       (address_reg[0]));
  DFFRHQX1 \address_reg_reg[6] (.RN (n_107), .CK (scl), .D (n_90), .Q
       (address_reg[6]));
  DFFRHQX1 \address_reg_reg[4] (.RN (n_107), .CK (scl), .D (n_85), .Q
       (address_reg[4]));
  OAI211X1 g1594__6783(.A0 (n_4), .A1 (n_92), .B0 (n_97), .C0 (n_82),
       .Y (n_98));
  DFFRHQX1 \address_reg_reg[2] (.RN (n_107), .CK (scl), .D (n_91), .Q
       (address_reg[2]));
  DFFRHQX1 \address_reg_reg[7] (.RN (n_107), .CK (scl), .D (n_71), .Q
       (address_reg[7]));
  DFFRHQX1 \address_reg_reg[5] (.RN (n_107), .CK (scl), .D (n_79), .Q
       (address_reg[5]));
  OAI2BB1X1 g1593__3680(.A0N (sda), .A1N (n_60), .B0 (n_81), .Y (n_96));
  INVXL g1617(.A (n_93), .Y (n_95));
  AOI32X1 g1643__1617(.A0 (state[0]), .A1 (start_event), .A2 (n_26),
       .B0 (n_88), .B1 (n_87), .Y (n_103));
  NOR2XL g1623__2802(.A (n_64), .B (n_40), .Y (n_94));
  OAI31X1 g1620__1705(.A0 (address_reg[0]), .A1 (state[0]), .A2 (n_92),
       .B0 (n_97), .Y (n_93));
  SDFFRHQX1 \data_received_reg[2] (.RN (n_107), .CK (scl), .D (sda),
       .SI (data_received[2]), .SE (n_53), .Q (data_received[2]));
  SDFFRHQX1 \data_received_reg[5] (.RN (n_107), .CK (scl), .D (sda),
       .SI (data_received[5]), .SE (n_50), .Q (data_received[5]));
  SDFFRHQX1 \data_received_reg[4] (.RN (n_107), .CK (scl), .D (sda),
       .SI (data_received[4]), .SE (n_55), .Q (data_received[4]));
  INVXL g1601(.A (n_77), .Y (n_91));
  INVXL g1604(.A (n_72), .Y (n_90));
  NAND2XL g1648__5122(.A (n_88), .B (n_87), .Y (n_89));
  AOI22XL g1657__8246(.A0 (n_88), .A1 (n_58), .B0 (sda_drive_en), .B1
       (n_2), .Y (n_86));
  INVXL g1592(.A (n_83), .Y (n_85));
  NOR2XL g1615__7098(.A (n_70), .B (n_66), .Y (n_84));
  AOI32X1 g1600__6131(.A0 (sda), .A1 (n_54), .A2 (n_121), .B0
       (address_reg[4]), .B1 (n_46), .Y (n_83));
  AOI33XL g1621__1881(.A0 (state[2]), .A1 (n_61), .A2 (n_56), .B0
       (state[1]), .B1 (state[0]), .B2 (n_47), .Y (n_82));
  SDFFRHQX1 \data_received_reg[0] (.RN (n_107), .CK (scl), .D
       (data_received[0]), .SI (sda), .SE (n_38), .Q
       (data_received[0]));
  SDFFRHQX1 \data_received_reg[1] (.RN (n_107), .CK (scl), .D
       (data_received[1]), .SI (sda), .SE (n_22), .Q
       (data_received[1]));
  SDFFRHQX1 \data_received_reg[6] (.RN (n_107), .CK (scl), .D
       (data_received[6]), .SI (sda), .SE (n_23), .Q
       (data_received[6]));
  SDFFRHQX1 \data_received_reg[7] (.RN (n_107), .CK (scl), .D
       (data_received[7]), .SI (sda), .SE (n_36), .Q
       (data_received[7]));
  SDFFRHQX1 \data_received_reg[3] (.RN (n_107), .CK (scl), .D
       (data_received[3]), .SI (sda), .SE (n_29), .Q
       (data_received[3]));
  OAI2BB1X1 g1613__5115(.A0N (n_44), .A1N (n_80), .B0 (address_reg[0]),
       .Y (n_81));
  INVXL g1603(.A (n_62), .Y (n_79));
  OAI32X1 g1605__7482(.A0 (n_74), .A1 (n_63), .A2 (n_73), .B0 (n_12),
       .B1 (n_32), .Y (n_78));
  AOI32X1 g1606__4733(.A0 (sda), .A1 (n_52), .A2 (n_121), .B0
       (address_reg[2]), .B1 (n_41), .Y (n_77));
  OAI32X1 g1608__6161(.A0 (n_67), .A1 (n_74), .A2 (n_73), .B0 (n_39),
       .B1 (n_48), .Y (n_75));
  AOI32X1 g1610__9315(.A0 (sda), .A1 (n_42), .A2 (n_121), .B0
       (address_reg[6]), .B1 (n_43), .Y (n_72));
  INVXL g1602(.A (n_65), .Y (n_71));
  OAI33X1 g1641__9945(.A0 (data_to_send[4]), .A1 (n_68), .A2 (n_69),
       .B0 (n_68), .B1 (data_to_send[3]), .B2 (n_67), .Y (n_70));
  OAI33X1 g1642__2883(.A0 (data_to_send[5]), .A1 (n_68), .A2 (n_16),
       .B0 (n_68), .B1 (data_to_send[6]), .B2 (n_20), .Y (n_66));
  AOI32X1 g1607__2346(.A0 (sda), .A1 (n_35), .A2 (n_121), .B0
       (address_reg[7]), .B1 (n_33), .Y (n_65));
  OAI33X1 g1654__1666(.A0 (data_to_send[1]), .A1 (n_68), .A2 (n_63),
       .B0 (n_68), .B1 (data_to_send[2]), .B2 (n_19), .Y (n_64));
  AOI32X1 g1609__7410(.A0 (sda), .A1 (n_49), .A2 (n_121), .B0
       (address_reg[5]), .B1 (n_30), .Y (n_62));
  OAI21XL g1668__6417(.A0 (state[1]), .A1 (n_61), .B0 (n_92), .Y
       (n_87));
  INVXL g1622(.A (n_59), .Y (n_60));
  INVXL g1676(.A (n_92), .Y (n_58));
  AOI31X1 g1616__5477(.A0 (state[0]), .A1 (state[2]), .A2
       (start_event), .B0 (n_56), .Y (n_57));
  NAND2XL g1630__2398(.A (n_54), .B (n_51), .Y (n_55));
  NAND2XL g1629__5107(.A (n_52), .B (n_51), .Y (n_53));
  NAND2XL g1625__6260(.A (n_49), .B (n_51), .Y (n_50));
  AOI21XL g1635__4319(.A0 (state[0]), .A1 (n_67), .B0 (n_31), .Y
       (n_48));
  NAND2XL g1632__8428(.A (n_47), .B (n_121), .Y (n_59));
  OAI21XL g1636__5526(.A0 (n_45), .A1 (n_54), .B0 (n_44), .Y (n_46));
  OAI21XL g1637__6783(.A0 (n_45), .A1 (n_42), .B0 (n_44), .Y (n_43));
  OAI21XL g1640__3680(.A0 (n_45), .A1 (n_52), .B0 (n_44), .Y (n_41));
  OAI32X1 g1655__1617(.A0 (data_to_send[0]), .A1 (n_68), .A2 (n_37),
       .B0 (state[0]), .B1 (n_68), .Y (n_40));
  INVXL g1652(.A (n_56), .Y (n_80));
  NAND4XL g1680__2802(.A (state[1]), .B (address_reg[2]), .C (n_39), .D
       (n_13), .Y (n_92));
  NOR2XL g1628__1705(.A (n_34), .B (n_37), .Y (n_38));
  NOR2BX1 g1631__5122(.AN (n_35), .B (n_34), .Y (n_36));
  OAI21XL g1634__8246(.A0 (n_45), .A1 (n_35), .B0 (n_44), .Y (n_33));
  AOI21XL g1638__7098(.A0 (state[0]), .A1 (n_63), .B0 (n_31), .Y
       (n_32));
  OAI21XL g1639__6131(.A0 (n_45), .A1 (n_49), .B0 (n_44), .Y (n_30));
  NOR2XL g1624__1881(.A (n_67), .B (n_34), .Y (n_29));
  INVXL g1644(.A (n_121), .Y (n_73));
  NAND3BXL g1656__7482(.AN (data_to_send[7]), .B (n_26), .C (n_35), .Y
       (n_27));
  NOR2BX1 g1627__6161(.AN (n_42), .B (n_34), .Y (n_23));
  NOR2XL g1626__9315(.A (n_63), .B (n_34), .Y (n_22));
  DFFNSRX1 start_event_reg(.RN (n_107), .SN (1'b1), .CKN (sda), .D
       (n_17), .Q (start_event), .QN (n_61));
  NOR2XL g1659__9945(.A (n_45), .B (n_47), .Y (n_56));
  INVXL g1666(.A (n_42), .Y (n_20));
  INVXL g1645(.A (n_34), .Y (n_51));
  INVXL g1675(.A (n_52), .Y (n_19));
  NAND2XL g1614__2346(.A (counter[0]), .B (n_24), .Y (n_18));
  INVXL g1667(.A (n_54), .Y (n_69));
  NOR3BXL g1599__1666(.AN (n_88), .B (n_0), .C (state[1]), .Y (n_17));
  INVXL g1661(.A (n_49), .Y (n_16));
  AOI21XL g1658__7410(.A0 (state[0]), .A1 (n_15), .B0 (n_14), .Y
       (n_104));
  INVXL g1653(.A (n_44), .Y (n_31));
  INVXL g1633(.A (sda), .Y (n_74));
  NAND2XL g1651__6417(.A (state[1]), .B (n_14), .Y (n_34));
  AND4XL g1688__5477(.A (address_reg[6]), .B (address_reg[4]), .C
       (n_12), .D (n_1), .Y (n_13));
  INVXL g1682(.A (n_37), .Y (n_47));
  NOR2XL g1670__2398(.A (n_5), .B (n_11), .Y (n_42));
  NOR2XL g1671__5107(.A (counter[1]), .B (n_11), .Y (n_54));
  NAND2XL g1664__6260(.A (counter[0]), .B (n_10), .Y (n_67));
  NOR2BX1 g1679__4319(.AN (n_10), .B (counter[0]), .Y (n_52));
  OR2X1 g1646__8428(.A (counter[0]), .B (n_7), .Y (n_9));
  NAND2XL g1649__5526(.A (state[0]), .B (n_97), .Y (n_24));
  AOI211XL g1660__6783(.A0 (n_61), .A1 (n_45), .B0 (state[2]), .C0
       (state[1]), .Y (n_44));
  INVXL g1684(.A (n_68), .Y (n_26));
  NAND2XL g1683__3680(.A (n_3), .B (n_7), .Y (n_37));
  NOR2XL g1663__1617(.A (counter[1]), .B (n_6), .Y (n_49));
  NOR2XL g1662__2802(.A (n_5), .B (n_6), .Y (n_35));
  NAND2XL g1674__1705(.A (counter[0]), .B (n_7), .Y (n_63));
  NAND2XL g1647__5122(.A (address_reg[0]), .B (n_45), .Y (n_4));
  NAND2XL g1678__8246(.A (counter[2]), .B (n_3), .Y (n_11));
  NOR2XL g1685__7098(.A (counter[2]), .B (n_5), .Y (n_10));
  INVXL g1677(.A (n_97), .Y (n_2));
  NOR2XL g1669__6131(.A (state[2]), .B (n_45), .Y (n_14));
  NAND2XL g1686__1881(.A (state[2]), .B (n_15), .Y (n_68));
  TBUFXL g1__5115(.A (1'b0), .OE (sda_drive_en), .Y (sda));
  NOR2XL g1687__7482(.A (counter[1]), .B (counter[2]), .Y (n_7));
  NOR2XL g1673__4733(.A (state[0]), .B (state[2]), .Y (n_88));
  NOR2XL g1689__6161(.A (address_reg[5]), .B (address_reg[7]), .Y
       (n_1));
  NAND2XL g1672__9315(.A (counter[0]), .B (counter[2]), .Y (n_6));
  NAND2XL g1681__9945(.A (state[1]), .B (state[2]), .Y (n_97));
  INVXL g1698(.A (scl), .Y (n_0));
  INVXL g1697(.A (rst), .Y (n_107));
  OAI21X1 g2(.A0 (n_24), .A1 (counter[0]), .B0 (counter[1]), .Y
       (n_119));
  OAI21XL g1723(.A0 (n_24), .A1 (counter[1]), .B0 (counter[2]), .Y
       (n_120));
  DFFRX1 \counter_reg[0] (.RN (n_107), .CK (scl), .D (n_106), .Q
       (counter[0]), .QN (n_3));
  DFFRX1 \state_reg[1] (.RN (n_107), .CK (scl), .D (n_102), .Q
       (state[1]), .QN (n_15));
  DFFRX1 \state_reg[0] (.RN (n_107), .CK (scl), .D (n_99), .Q
       (state[0]), .QN (n_45));
  DFFRX1 \address_reg_reg[1] (.RN (n_107), .CK (scl), .D (n_78), .Q
       (address_reg[1]), .QN (n_12));
  DFFRX1 \address_reg_reg[3] (.RN (n_107), .CK (scl), .D (n_75), .Q
       (address_reg[3]), .QN (n_39));
  DFFRX1 \counter_reg[1] (.RN (n_107), .CK (scl), .D (n_105), .Q
       (counter[1]), .QN (n_5));
  NOR2BX1 g1736(.AN (n_14), .B (state[1]), .Y (n_121));
endmodule